const rows=[
['Qual planeta é conhecido como Planeta Vermelho?','Marte',['Marte','Vênus','Júpiter','Mercúrio'],'Ciências'],
['Qual é a capital do Japão?','Tóquio',['Tóquio','Pequim','Seul','Bangkok'],'Geografia'],
['Quanto é 12 × 8?','96',['96','86','108','88'],'Matemática'],
['Quem pintou a Mona Lisa?','Leonardo da Vinci',['Leonardo da Vinci','Michelangelo','Van Gogh','Pablo Picasso'],'Arte'],
['Qual é o maior oceano da Terra?','Pacífico',['Pacífico','Atlântico','Índico','Ártico'],'Geografia'],
['Qual gás as plantas absorvem principalmente?','Dióxido de carbono',['Dióxido de carbono','Oxigênio','Hidrogênio','Hélio'],'Ciências'],
['Em qual país ficam as pirâmides de Gizé?','Egito',['Egito','México','Índia','Grécia'],'História'],
['Qual é o resultado de 144 ÷ 12?','12',['12','14','10','16'],'Matemática'],
['Qual animal é o maior mamífero do mundo?','Baleia-azul',['Baleia-azul','Elefante-africano','Girafa','Tubarão-branco'],'Natureza'],
['Qual idioma é falado oficialmente no Brasil?','Português',['Português','Espanhol','Inglês','Francês'],'Conhecimentos gerais'],
['Qual é o símbolo químico do ouro?','Au',['Au','Ag','O','Fe'],'Ciências'],
['Em que continente fica o deserto do Saara?','África',['África','Ásia','América','Oceania'],'Geografia'],
['Qual instrumento mede a temperatura?','Termômetro',['Termômetro','Barômetro','Higrômetro','Telescópio'],'Ciências'],
['Quantos lados possui um hexágono?','6',['6','5','7','8'],'Matemática'],
['Qual é o satélite natural da Terra?','Lua',['Lua','Sol','Marte','Vênus'],'Ciências'],
['Quem escreveu Dom Casmurro?','Machado de Assis',['Machado de Assis','José de Alencar','Clarice Lispector','Carlos Drummond'],'Literatura'],
['Qual país tem o formato frequentemente comparado a uma bota?','Itália',['Itália','Portugal','Chile','Noruega'],'Geografia'],
['Qual é a raiz quadrada de 81?','9',['9','8','7','6'],'Matemática'],
['Qual órgão bombeia o sangue pelo corpo?','Coração',['Coração','Pulmão','Fígado','Rim'],'Ciências'],
['Qual é o menor número primo?','2',['2','1','3','0'],'Matemática'],
['Qual empresa criou o console PlayStation?','Sony',['Sony','Nintendo','Microsoft','Sega'],'Jogos'],
['Qual personagem usa uma roupa verde e salva Hyrule?','Link',['Link','Mario','Sonic','Kirby'],'Jogos'],
['Em Minecraft, qual material é necessário para criar uma mesa de encantamentos?','Obsidiana',['Obsidiana','Cobre','Areia','Lã'],'Jogos'],
['Qual jogo possui a frase Victory Royale?','Fortnite',['Fortnite','Valorant','Minecraft','Roblox'],'Jogos'],
['Qual empresa desenvolveu Clash Royale?','Supercell',['Supercell','Riot Games','Valve','Mojang'],'Jogos'],
['Qual Pokémon evolui para Raichu?','Pikachu',['Pikachu','Charmander','Eevee','Meowth'],'Jogos'],
['Qual é o nome do irmão de Mario?','Luigi',['Luigi','Wario','Toad','Yoshi'],'Jogos'],
['Qual jogo possui agentes como Jett e Sage?','Valorant',['Valorant','Overwatch','Apex Legends','Counter-Strike'],'Jogos'],
['Qual mascote azul pertence à Sega?','Sonic',['Sonic','Mega Man','Stitch','Squirtle'],'Jogos'],
['Qual jogo usa uma bola gigante e carros?','Rocket League',['Rocket League','Forza Horizon','Gran Turismo','Need for Speed'],'Jogos'],
['Qual é a capital da Argentina?','Buenos Aires',['Buenos Aires','Santiago','Lima','Montevidéu'],'Geografia'],
['Quantos minutos existem em duas horas?','120',['120','100','90','140'],'Matemática'],
['Qual camada protege a Terra de parte da radiação ultravioleta?','Camada de ozônio',['Camada de ozônio','Crosta terrestre','Ionosfera','Manto'],'Ciências'],
['Qual é o maior país do mundo em área territorial?','Rússia',['Rússia','Canadá','China','Brasil'],'Geografia'],
['Quem formulou as três leis do movimento clássico?','Isaac Newton',['Isaac Newton','Albert Einstein','Galileu Galilei','Charles Darwin'],'Ciências'],
['Qual movimento da Terra causa os dias e as noites?','Rotação',['Rotação','Translação','Precessão','Revolução lunar'],'Ciências'],
['Qual é o plural de pão?','Pães',['Pães','Pãos','Pões','Pãeses'],'Português'],
['Qual palavra é sinônimo de rápido?','Veloz',['Veloz','Lento','Fraco','Distante'],'Português'],
['Em qual estado brasileiro fica Salvador?','Bahia',['Bahia','Ceará','Pernambuco','Sergipe'],'Geografia'],
['Qual é a capital de Minas Gerais?','Belo Horizonte',['Belo Horizonte','Vitória','Goiânia','Curitiba'],'Geografia'],
['Qual bioma ocupa grande parte da Região Norte do Brasil?','Amazônia',['Amazônia','Pampa','Caatinga','Pantanal'],'Geografia'],
['Em que ano ocorreu a Independência do Brasil?','1822',['1822','1889','1500','1808'],'História'],
['Quem foi o primeiro imperador do Brasil?','Dom Pedro I',['Dom Pedro I','Dom Pedro II','Getúlio Vargas','Deodoro da Fonseca'],'História'],
['Qual civilização construiu Machu Picchu?','Inca',['Inca','Maia','Asteca','Romana'],'História'],
['Qual é a fórmula química da água?','H₂O',['H₂O','CO₂','O₂','NaCl'],'Ciências'],
['Quantos dentes costuma ter um adulto com a dentição completa?','32',['32','28','30','36'],'Ciências'],
['Qual metal é líquido próximo da temperatura ambiente?','Mercúrio',['Mercúrio','Ferro','Alumínio','Cobre'],'Ciências'],
['Qual é o maior órgão do corpo humano?','Pele',['Pele','Fígado','Cérebro','Pulmão'],'Ciências'],
['Qual processo transforma água líquida em vapor?','Evaporação',['Evaporação','Condensação','Solidificação','Fusão'],'Ciências'],
['Qual número romano representa 50?','L',['L','C','X','V'],'Matemática'],
['Quanto é 15% de 200?','30',['30','25','20','35'],'Matemática'],
['Um triângulo com três lados iguais é chamado de quê?','Equilátero',['Equilátero','Isósceles','Escaleno','Retângulo'],'Matemática'],
['Qual é o valor aproximado de π com duas casas decimais?','3,14',['3,14','3,41','2,14','4,13'],'Matemática'],
['Quem é o deus do trovão na mitologia nórdica?','Thor',['Thor','Loki','Odin','Tyr'],'Mitologia'],
['Qual instrumento possui teclas pretas e brancas?','Piano',['Piano','Violino','Flauta','Tambor'],'Música'],
['Qual cor resulta da mistura de azul com amarelo?','Verde',['Verde','Roxo','Laranja','Rosa'],'Arte'],
['Qual esporte utiliza uma cesta e uma bola laranja?','Basquete',['Basquete','Vôlei','Tênis','Beisebol'],'Esportes'],
['Quantos jogadores cada time tem em campo no futebol tradicional?','11',['11','10','12','9'],'Esportes'],
['Em qual esporte é usado o termo xeque-mate?','Xadrez',['Xadrez','Damas','Tênis','Judô'],'Esportes'],
['Qual país venceu a Copa do Mundo masculina de 2002?','Brasil',['Brasil','Alemanha','França','Argentina'],'Esportes']
];

const BATTLE_QUESTIONS=rows.map((r,i)=>({id:`battle-${i+1}`,prompt:r[0],answer:r[1],choices:r[2],topic:r[3]}));
module.exports={BATTLE_QUESTIONS};
