// 100 jogos x 5 desafios factuais = 500 novas perguntas.
// Campos: título, ano de lançamento original, desenvolvedora, protagonista, gênero e cenário.
const games = [
  ["Super Mario Bros.","1985","Nintendo","Mario","plataforma","Reino dos Cogumelos"],
  ["The Legend of Zelda","1986","Nintendo","Link","ação e aventura","Hyrule"],
  ["Metroid","1986","Nintendo R&D1","Samus Aran","ação e aventura","planeta Zebes"],
  ["Mega Man","1987","Capcom","Mega Man","plataforma e ação","ano 20XX"],
  ["Final Fantasy","1987","Square","Guerreiro da Luz","RPG","mundo de Cornelia"],
  ["Sonic the Hedgehog","1991","Sonic Team","Sonic","plataforma","South Island"],
  ["Street Fighter II","1991","Capcom","Ryu","luta","torneio mundial"],
  ["Mortal Kombat","1992","Midway","Liu Kang","luta","Earthrealm"],
  ["Kirby's Dream Land","1992","HAL Laboratory","Kirby","plataforma","Dream Land"],
  ["Doom","1993","id Software","Doom Slayer","tiro em primeira pessoa","Marte e o Inferno"],
  ["Donkey Kong Country","1994","Rare","Donkey Kong","plataforma","Ilha Donkey Kong"],
  ["EarthBound","1994","APE e HAL Laboratory","Ness","RPG","Eagleland"],
  ["Chrono Trigger","1995","Square","Crono","RPG","diferentes eras do tempo"],
  ["Rayman","1995","Ubisoft Montpellier","Rayman","plataforma","The Glade of Dreams"],
  ["Resident Evil","1996","Capcom","Jill Valentine e Chris Redfield","survival horror","Mansão Spencer"],
  ["Crash Bandicoot","1996","Naughty Dog","Crash Bandicoot","plataforma","Ilhas Wumpa"],
  ["Tomb Raider","1996","Core Design","Lara Croft","ação e aventura","ruínas ao redor do mundo"],
  ["Quake","1996","id Software","Ranger","tiro em primeira pessoa","dimensões sombrias"],
  ["Castlevania: Symphony of the Night","1997","Konami","Alucard","ação e exploração","castelo de Drácula"],
  ["Final Fantasy VII","1997","Square","Cloud Strife","RPG","Gaia"],
  ["Fallout","1997","Interplay Productions","Vault Dweller","RPG","Wasteland"],
  ["Banjo-Kazooie","1998","Rare","Banjo e Kazooie","plataforma 3D","Spiral Mountain"],
  ["Half-Life","1998","Valve","Gordon Freeman","tiro em primeira pessoa","Black Mesa"],
  ["Metal Gear Solid","1998","Konami","Solid Snake","ação furtiva","Shadow Moses"],
  ["Spyro the Dragon","1998","Insomniac Games","Spyro","plataforma 3D","Dragon Realms"],
  ["Silent Hill","1999","Team Silent","Harry Mason","terror psicológico","Silent Hill"],
  ["Shenmue","1999","Sega AM2","Ryo Hazuki","ação e aventura","Yokosuka"],
  ["Deus Ex","2000","Ion Storm","JC Denton","RPG de ação","futuro distópico de 2052"],
  ["Diablo II","2000","Blizzard North","herói de Santuário","RPG de ação","Santuário"],
  ["Paper Mario","2000","Intelligent Systems","Mario","RPG","Reino dos Cogumelos"],
  ["Halo: Combat Evolved","2001","Bungie","Master Chief","tiro em primeira pessoa","anel Halo"],
  ["Max Payne","2001","Remedy Entertainment","Max Payne","tiro em terceira pessoa","Nova York"],
  ["Devil May Cry","2001","Capcom","Dante","ação hack and slash","Ilha Mallet"],
  ["Luigi's Mansion","2001","Nintendo","Luigi","ação e aventura","mansão assombrada"],
  ["Kingdom Hearts","2002","Square","Sora","RPG de ação","diversos mundos da Disney"],
  ["Metroid Prime","2002","Retro Studios","Samus Aran","ação e aventura em primeira pessoa","Tallon IV"],
  ["Ratchet & Clank","2002","Insomniac Games","Ratchet e Clank","plataforma e ação","Galáxia Solana"],
  ["The Legend of Zelda: The Wind Waker","2002","Nintendo","Link","ação e aventura","Grande Mar"],
  ["Prince of Persia: The Sands of Time","2003","Ubisoft Montreal","Príncipe da Pérsia","ação e aventura","Pérsia"],
  ["Beyond Good & Evil","2003","Ubisoft Montpellier","Jade","ação e aventura","Hillys"],
  ["Star Wars: Knights of the Old Republic","2003","BioWare","Revan","RPG","galáxia de Star Wars"],
  ["Half-Life 2","2004","Valve","Gordon Freeman","tiro em primeira pessoa","City 17"],
  ["God of War","2005","Santa Monica Studio","Kratos","ação hack and slash","Grécia mitológica"],
  ["Psychonauts","2005","Double Fine Productions","Razputin Aquato","plataforma","acampamento Whispering Rock"],
  ["Shadow of the Colossus","2005","Team Ico","Wander","ação e aventura","Terras Proibidas"],
  ["Okami","2006","Clover Studio","Amaterasu","ação e aventura","Nippon"],
  ["Gears of War","2006","Epic Games","Marcus Fenix","tiro em terceira pessoa","planeta Sera"],
  ["Portal","2007","Valve","Chell","quebra-cabeça em primeira pessoa","Aperture Science"],
  ["BioShock","2007","2K Boston e 2K Australia","Jack","tiro em primeira pessoa","Rapture"],
  ["Assassin's Creed","2007","Ubisoft Montreal","Altaïr Ibn-La'Ahad","ação e aventura","Terra Santa"],
  ["Uncharted: Drake's Fortune","2007","Naughty Dog","Nathan Drake","ação e aventura","ilha tropical misteriosa"],
  ["Mass Effect","2007","BioWare","Comandante Shepard","RPG de ação","Via Láctea"],
  ["Dead Space","2008","EA Redwood Shores","Isaac Clarke","survival horror","USG Ishimura"],
  ["Mirror's Edge","2008","DICE","Faith Connors","ação e plataforma em primeira pessoa","City of Glass"],
  ["Left 4 Dead","2008","Valve South","Bill, Zoey, Louis e Francis","tiro cooperativo","Pensilvânia durante uma epidemia"],
  ["Bayonetta","2009","PlatinumGames","Bayonetta","ação hack and slash","Vigrid"],
  ["Batman: Arkham Asylum","2009","Rocksteady Studios","Batman","ação e aventura","Asilo Arkham"],
  ["Dragon Age: Origins","2009","BioWare","Guardião Cinzento","RPG","Ferelden"],
  ["Minecraft","2011","Mojang Studios","Steve e Alex","sandbox de sobrevivência","mundo de blocos gerado proceduralmente"],
  ["Dark Souls","2011","FromSoftware","Morto-Vivo Escolhido","RPG de ação","Lordran"],
  ["The Elder Scrolls V: Skyrim","2011","Bethesda Game Studios","Dragonborn","RPG de mundo aberto","Skyrim"],
  ["Portal 2","2011","Valve","Chell","quebra-cabeça em primeira pessoa","Aperture Science"],
  ["L.A. Noire","2011","Team Bondi","Cole Phelps","aventura policial","Los Angeles"],
  ["Journey","2012","Thatgamecompany","viajante","aventura","deserto misterioso"],
  ["Dishonored","2012","Arkane Studios","Corvo Attano","ação furtiva","Dunwall"],
  ["Hotline Miami","2012","Dennaton Games","Jacket","ação vista de cima","Miami"],
  ["The Last of Us","2013","Naughty Dog","Joel e Ellie","ação e aventura","Estados Unidos pós-pandemia"],
  ["BioShock Infinite","2013","Irrational Games","Booker DeWitt","tiro em primeira pessoa","Columbia"],
  ["Tomb Raider (2013)","2013","Crystal Dynamics","Lara Croft","ação e aventura","ilha Yamatai"],
  ["Grand Theft Auto V","2013","Rockstar North","Michael, Franklin e Trevor","ação em mundo aberto","Los Santos"],
  ["Five Nights at Freddy's","2014","Scott Cawthon","Mike Schmidt","terror e sobrevivência","Freddy Fazbear's Pizza"],
  ["Alien: Isolation","2014","Creative Assembly","Amanda Ripley","survival horror","estação Sevastopol"],
  ["Shovel Knight","2014","Yacht Club Games","Shovel Knight","plataforma e ação","Vale"],
  ["Ori and the Blind Forest","2015","Moon Studios","Ori","plataforma e exploração","floresta de Nibel"],
  ["Undertale","2015","Toby Fox","Frisk","RPG","Subsolo"],
  ["The Witcher 3: Wild Hunt","2015","CD Projekt Red","Geralt de Rívia","RPG de ação","Continente"],
  ["Life is Strange","2015","Dontnod Entertainment","Max Caulfield","aventura narrativa","Arcadia Bay"],
  ["Bloodborne","2015","FromSoftware","Caçador","RPG de ação","Yharnam"],
  ["Firewatch","2016","Campo Santo","Henry","aventura narrativa","Floresta Nacional de Shoshone"],
  ["Stardew Valley","2016","ConcernedApe","fazendeiro","simulação e RPG","Pelican Town"],
  ["Titanfall 2","2016","Respawn Entertainment","Jack Cooper","tiro em primeira pessoa","Fronteira"],
  ["Inside","2016","Playdead","garoto sem nome","quebra-cabeça e plataforma","mundo distópico"],
  ["Horizon Zero Dawn","2017","Guerrilla Games","Aloy","RPG de ação","Terra pós-apocalíptica"],
  ["Cuphead","2017","Studio MDHR","Cuphead","ação e plataforma","Ilhas Tinteiro"],
  ["Hollow Knight","2017","Team Cherry","Cavaleiro","metroidvania","Hallownest"],
  ["NieR: Automata","2017","PlatinumGames","2B","RPG de ação","Terra em futuro distante"],
  ["Super Mario Odyssey","2017","Nintendo EPD","Mario","plataforma 3D","diversos reinos"],
  ["Celeste","2018","Matt Makes Games","Madeline","plataforma","Montanha Celeste"],
  ["God of War (2018)","2018","Santa Monica Studio","Kratos e Atreus","ação e aventura","reinos nórdicos"],
  ["Red Dead Redemption 2","2018","Rockstar Studios","Arthur Morgan","ação em mundo aberto","Velho Oeste americano"],
  ["Marvel's Spider-Man","2018","Insomniac Games","Peter Parker","ação e aventura","Nova York"],
  ["Sekiro: Shadows Die Twice","2019","FromSoftware","Lobo","ação e aventura","Japão do período Sengoku"],
  ["Control","2019","Remedy Entertainment","Jesse Faden","ação e aventura","Casa Mais Antiga"],
  ["Death Stranding","2019","Kojima Productions","Sam Porter Bridges","ação e aventura","Estados Unidos fragmentados"],
  ["Hades","2020","Supergiant Games","Zagreu","roguelike de ação","Submundo grego"],
  ["Ghost of Tsushima","2020","Sucker Punch Productions","Jin Sakai","ação e aventura","ilha de Tsushima"],
  ["Ori and the Will of the Wisps","2020","Moon Studios","Ori","plataforma e exploração","Niwen"],
  ["Resident Evil Village","2021","Capcom","Ethan Winters","survival horror","vilarejo europeu"],
  ["Psychonauts 2","2021","Double Fine Productions","Razputin Aquato","plataforma","Psychonauts"],
  ["Elden Ring","2022","FromSoftware","Maculado","RPG de ação","Terras Intermédias"]
];

function initialHint(value){
  const clean=String(value).replace(/^(The|A|O|Os|As)\s+/i,'');
  return `A resposta começa com ${clean.charAt(0).toUpperCase()}.`;
}

const EXTRA_GAME_ROWS=games.flatMap(([title,year,developer,hero,genre,setting])=>[
  [`Qual é o jogo descrito: ${genre}, lançado em ${year}, com ${hero} como protagonista?`,title,[],[`Foi lançado originalmente em ${year}.`,`Foi desenvolvido por ${developer}.`,`É do gênero ${genre}.`,`Sua história ou exploração passa por ${setting}.`,initialHint(title)],`${title} foi lançado em ${year} e desenvolvido por ${developer}.`],
  [`Em que ano ${title} foi lançado originalmente?`,year,[],[`O jogo foi desenvolvido por ${developer}.`,`Seu gênero principal é ${genre}.`,`A aventura envolve ${hero}.`,`O cenário inclui ${setting}.`,`O ano pertence à década de ${year.slice(0,3)}0.`],`${title} teve seu lançamento original em ${year}.`],
  [`Qual estúdio desenvolveu ${title}?`,developer,[],[`O jogo chegou originalmente em ${year}.`,`É uma produção do gênero ${genre}.`,`Seu protagonista é ${hero}.`,`A aventura acontece em ${setting}.`,initialHint(developer)],`${developer} foi responsável pelo desenvolvimento de ${title}.`],
  [`Quem protagoniza ${title}?`,hero,[],[`O jogo foi lançado em ${year}.`,`Foi desenvolvido por ${developer}.`,`É um título de ${genre}.`,`A história passa por ${setting}.`,initialHint(hero)],`${hero} protagoniza ${title}.`],
  [`Qual é o principal cenário de ${title}?`,setting,[],[`O jogo foi lançado em ${year}.`,`Foi desenvolvido por ${developer}.`,`Seu protagonista é ${hero}.`,`Seu gênero principal é ${genre}.`,initialHint(setting)],`${title} se passa principalmente em ${setting}.`]
]);

module.exports={EXTRA_GAME_ROWS};
