'use strict';
const crypto=require('crypto'),engine=require('./rpg_match');
const uid=()=>crypto.randomUUID(),fail=(m,status=400)=>{throw Object.assign(Error(m),{status});};
const MAX_TEAMS=32,MAX_YEARS=100,MAX_BYTES=3*1024*1024;
const RULES='Vitória: 3 pontos; empate: 1. Desempate: pontos, saldo de gols, gols marcados, vitórias e ordem do sorteio inicial. Champions: grupos de quatro, ida e volta; dois classificados por grupo; mata-mata em ida e volta e final única, sem gol fora. Empate no agregado exige vencedor por prorrogação/pênaltis. Simulações têm chances iguais e não usam atributos. Regras da adaptação digital.';
function fresh(){return {version:1,rev:0,year:2026,teams:{},followed:null,season:null,history:[],match:null,active:null};}
function shuffle(ids){const a=[...ids];for(let i=a.length-1;i>0;i--){const j=crypto.randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function fixture(home,away,extra={}){return {id:uid(),home,away,score:null,winner:null,...extra};}
function robin(ids,twice=true){const a=[...ids];if(a.length%2)a.push(null);const rounds=[];for(let r=0;r<a.length-1;r++){const games=[];for(let i=0;i<a.length/2;i++){let [h,v]=[a[i],a[a.length-1-i]];if(r%2)[h,v]=[v,h];if(h&&v)games.push(fixture(h,v));}rounds.push(games);a.splice(1,0,a.pop());}return twice?[...rounds,...rounds.map(gs=>gs.map(g=>fixture(g.away,g.home)))]:rounds;}
function table(ids,rounds){const stats=Object.fromEntries(ids.map((id,seed)=>[id,{id,seed,points:0,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0}]));for(const games of rounds)for(const g of games){if(!g.score||!stats[g.home]||!stats[g.away])continue;const [a,b]=g.score,h=stats[g.home],v=stats[g.away];h.played++;v.played++;h.gf+=a;h.ga+=b;v.gf+=b;v.ga+=a;if(a===b){h.draws++;v.draws++;h.points++;v.points++;}else{const [win,lose]=a>b?[h,v]:[v,h];win.wins++;win.points+=3;lose.losses++;}}return Object.values(stats).map(x=>({...x,gd:x.gf-x.ga})).sort((a,b)=>b.points-a.points||b.gd-a.gd||b.gf-a.gf||b.wins-a.wins||a.seed-b.seed);}
function knockout(ids){const final=ids.length===2,rounds=[[]];if(!final)rounds.push([]);for(let i=0;i<ids.length;i+=2){const tie=uid();rounds[0].push(fixture(ids[i],ids[i+1],{tie,leg:1,final}));if(!final)rounds[1].push(fixture(ids[i+1],ids[i],{tie,leg:2,final:false}));}return {kind:'knockout',label:final?'Final':ids.length===4?'Semifinais':ids.length===8?'Quartas de final':'Oitavas de final',rounds};}
function comp(kind,ids,twice=true){const seeded=shuffle(ids);if(kind==='league')return {kind,status:'playing',ids:seeded,stages:[{kind:'league',label:'Pontos corridos',rounds:robin(seeded,twice)}],stage:0,round:0,champion:null,eliminated:false};const groups=[];for(let i=0;i<seeded.length;i+=4)groups.push(seeded.slice(i,i+4));const schedules=groups.map(g=>robin(g));return {kind,status:'playing',ids:seeded,groups,stages:[{kind:'groups',label:'Fase de grupos',rounds:Array.from({length:6},(_,r)=>schedules.flatMap((gs,i)=>gs[r].map(g=>({...g,group:i}))))}],stage:0,round:0,champion:null,eliminated:false};}
function current(q){return q.status==='playing'?q.stages[q.stage].rounds[q.round]:[];}
function aggregate(q,g,score){if(!g.tie)return null;if(g.final)return [...score];if(g.leg!==2)return null;const first=q.stages[q.stage].rounds[0].find(x=>x.tie===g.tie);if(!first?.score)fail('A partida de ida está pendente.');return [score[0]+first.score[1],score[1]+first.score[0]];}
function record(q,g,score,winner,source){if(g.score)fail('Este resultado já foi registrado.',409);if(!Array.isArray(score)||score.length!==2||score.some(n=>!Number.isInteger(n)||n<0||n>99))fail('Informe um placar inteiro de 0 a 99.');const sum=aggregate(q,g,score);let decided=null;if(sum){if(sum[0]===sum[1]){if(![g.home,g.away].includes(winner))fail('Empate no agregado: escolha quem avançou por prorrogação/pênaltis.');decided=winner;}else decided=sum[0]>sum[1]?g.home:g.away;}g.score=[...score];g.winner=decided;g.source=source;}
function simulate(q,g){const score=[crypto.randomInt(0,5),crypto.randomInt(0,5)];record(q,g,score,crypto.randomInt(2)?g.home:g.away,'simulation');}
function settle(q,followed){while(q.status==='playing'&&current(q).every(g=>g.score)){
 const stage=q.stages[q.stage];if(++q.round<stage.rounds.length)return;
 if(q.kind==='league'){q.champion=table(q.ids,stage.rounds)[0].id;q.status='finished';return;}
 let next;
 if(stage.kind==='groups'){const ranked=q.groups.map(ids=>table(ids,stage.rounds));next=[];for(let i=0;i<ranked.length;i+=2)next.push(ranked[i][0].id,ranked[i+1][1].id,ranked[i+1][0].id,ranked[i][1].id);}
 else{next=stage.rounds[stage.rounds.length-1].map(g=>g.winner);if(next.some(x=>!x))fail('Falta decidir um confronto.',409);}
 if(!next.includes(followed))q.eliminated=true;
 if(next.length===1){q.champion=next[0];q.status='finished';return;}
 q.stages.push(knockout(next));q.stage++;q.round=0;
 }}
function finishSimulated(q,followed){let guard=0;while(q.status==='playing'){if(++guard>100)fail('Calendário inválido.');for(const g of current(q))if(!g.score)simulate(q,g);settle(q,followed);}}
function summary(s,a){const names=Object.fromEntries(Object.entries(a.teams).map(([id,t])=>[id,t.name]));const league=table(s.league.ids,s.league.stages[0].rounds),champ=s.champions;return {year:s.year,followed:a.followed,names,leagueChampion:s.league.champion,championsChampion:champ.champion,leagueTable:league,championsPhase:champ.champion===a.followed?'Campeão':champ.stages.find(st=>st.kind==='knockout'&&st.rounds.some(gs=>gs.some(g=>g.score&&[g.home,g.away].includes(a.followed)&&g.winner&&g.winner!==a.followed)))?.label||'Fase de grupos'};}
function progress(a){const s=a.season;if(!s)return;for(const q of [s.league,s.champions])settle(q,a.followed);if(s.champions.eliminated)finishSimulated(s.champions,a.followed);if(s.league.status==='finished'&&s.champions.status==='finished'){a.history.push(summary(s,a));a.year++;a.season=null;a.match=null;a.active=null;}}
function assertPrep(a){if(a.season)fail('Edite os times na preparação da próxima temporada.',409);}
function checkedIds(a,ids,min,max){if(!Array.isArray(ids)||ids.length<min||ids.length>max||new Set(ids).size!==ids.length||ids.some(id=>!Object.hasOwn(a.teams,id)))fail('Selecione os times da competição.');return [...ids];}
function validateTeam(input,validateSheet,c){if(typeof input.name!=='string'||!input.name.trim()||input.name.length>40||!/^#[0-9a-f]{6}$/i.test(input.color||'')||!Object.hasOwn(engine.FORMATIONS,input.formation))fail('Confira nome, cor e formação do time.');if(!Array.isArray(input.roster)||input.roster.length!==7)fail('Monte sete fichas para o elenco.');const roster=input.roster.map(p=>{const controller=p.controller||c.owner;if(!Object.hasOwn(c.members,controller))fail('Responsável pelo personagem não pertence ao save.');const sheet=validateSheet({...p.sheet,photo:'',approved:true},{},true);return {id:p.id&&/^npc:career_[a-zA-Z0-9-]{16,80}$/.test(p.id)?p.id:'npc:career_'+uid(),controller,sheet};});if(new Set(roster.map(p=>p.id)).size!==7||roster.filter(p=>p.sheet.position==='Goleiro').length!==1)fail('O time precisa de seis jogadores de linha e um goleiro.');return {name:input.name.trim(),color:input.color,formation:input.formation,roster};}
function context(c){const a=c.career;if(!a?.active||!a.match)fail('Não há jogo do campeonato aberto.',404);const q=a.season?.[a.active.competition],g=q?.stages.flatMap(s=>s.rounds.flat()).find(g=>g.id===a.active.fixture);if(!g)fail('Confronto não encontrado.',409);const entries=Object.fromEntries([g.home,g.away].flatMap(id=>a.teams[id].roster.map(p=>[p.id,{nick:p.sheet.name,sheet:p.sheet,rolls:null}])));return {id:c.id,name:c.name,owner:c.owner,members:Object.fromEntries(Object.entries(c.members).map(([id,m])=>[id,{nick:m.nick}])),extras:entries,savedTeams:{},match:a.match,matchApi:'/api/rpg/campaigns/'+c.id+'/career/match',careerMatch:true};}
function command(c,k,input,{validateSheet,currentSheet,testMode=false}){
 if(c.owner!==k)fail('Somente o mestre organiza a carreira.',403);
 const a=c.career||(c.career=fresh());if(input.rev!==a.rev)fail('A carreira mudou. Atualize a tela antes de continuar.',409);
 const op=input.op;
 if(op==='team'){assertPrep(a);const id=input.id;if(typeof id!=='string'||!/^[a-zA-Z0-9-]{16,80}$/.test(id))fail('Identificador de time inválido.');if(!Object.hasOwn(a.teams,id)&&Object.keys(a.teams).length>=MAX_TEAMS)fail('Limite de 32 times na carreira.');const next=validateTeam(input.team,validateSheet,c);const others=Object.entries(a.teams).filter(([key])=>key!==id).flatMap(([,t])=>t.roster.map(p=>p.id));if(next.roster.some(p=>others.includes(p.id)))fail('Uma ficha do campeonato não pode estar em dois times.');a.teams[id]=next;}
 else if(op==='removeTeam'){assertPrep(a);if(a.history.some(h=>h.names[input.id]))fail('Times com histórico são preservados na carreira. Retire-os apenas das próximas inscrições.');delete a.teams[input.id];if(a.followed===input.id)a.followed=null;}
 else if(op==='start'){assertPrep(a);if(input.confirm!==true)fail('Confirme as regras e inscrições.');if(a.history.length>=MAX_YEARS)fail('Limite de 100 temporadas desta carreira.');const league=checkedIds(a,input.league,2,32),champions=checkedIds(a,input.champions,8,32);if(![8,16,32].includes(champions.length))fail('A Champions precisa de 8, 16 ou 32 times.');if(!league.includes(input.followed)||!champions.includes(input.followed))fail('Seu time deve participar das duas competições.');for(const id of new Set([...league,...champions]))validateTeam(a.teams[id],validateSheet,c);a.followed=input.followed;a.season={year:a.year,league:comp('league',league,input.doubleLeague!==false),champions:comp('champions',champions)};}
 else if(op==='demoFinish'){if(!testMode||input.confirm!==true)fail('Disponível apenas no ambiente local de teste.',403);if(a.active)fail('Conclua o jogo aberto antes de simular o teste.');if(!a.season)fail('Inicie uma temporada.');finishSimulated(a.season.league,a.followed);finishSimulated(a.season.champions,a.followed);progress(a);}
 else {
  const q=a.season?.[input.competition];if(!['league','champions'].includes(input.competition)||!q||q.status!=='playing')fail('Competição indisponível.');
  const games=current(q),g=games.find(g=>g.id===input.fixture);
  if(op==='simulate'){if(input.confirm!==true)fail('Confirme a simulação.');const remaining=games.filter(g=>!g.score&&![g.home,g.away].includes(a.followed));if(!remaining.length)fail('Não há jogos de outros times pendentes nesta rodada.',409);for(const game of remaining)simulate(q,game);progress(a);}
  else if(op==='open'){
   if(!g||g.score||![g.home,g.away].includes(a.followed))fail('Abra um jogo pendente do seu time.');if(a.active){if(a.active.fixture===g.id)return;fail('Confirme o resultado do campo aberto antes de abrir outro jogo.',409);}
   const teams=[g.home,g.away].map(id=>a.teams[id]),extra=Object.fromEntries(teams.flatMap(t=>t.roster.map(p=>[p.id,{nick:p.sheet.name,sheet:p.sheet}]))),proxy={owner:c.owner,members:c.members,extras:extra,match:null};engine.command(proxy,k,{op:'create',teams:teams.map(t=>({...t,ids:t.roster.map(p=>p.id)})),freeMode:true},currentSheet);a.match=proxy.match;for(const p of teams.flatMap(t=>t.roster))a.match.players[p.id].controller=p.controller;a.active={competition:input.competition,fixture:g.id};
  }else if(op==='result'){
   if(input.confirm!==true||!g||g.score||![g.home,g.away].includes(a.followed))fail('Confirme o placar de um confronto pendente do seu time.');
   if(a.active){if(a.active.fixture!==g.id)fail('Existe outro confronto no campo.',409);engine.clock(a.match);if(a.match.status!=='finished'||input.matchId!==a.match.id||input.matchRev!==a.match.rev||JSON.stringify(input.score)!==JSON.stringify(a.match.score))fail('Encerre a partida e confira novamente o placar do campo.',409);}
   record(q,g,input.score,input.winner,a.active?'played':'manual');a.match=null;a.active=null;progress(a);
  }else fail('Operação da carreira inválida.');
 }
 a.rev++;if(Buffer.byteLength(JSON.stringify(a))>MAX_BYTES)fail('A carreira atingiu o limite de armazenamento.');
}
function view(c){const a=structuredClone(c.career||fresh());if(a.match)a.match=engine.publicMatch({match:a.match});return {...a,rules:RULES,limits:{teams:MAX_TEAMS,years:MAX_YEARS},tables:a.season?{league:table(a.season.league.ids,a.season.league.stages[0].rounds),groups:a.season.champions.groups.map(ids=>table(ids,a.season.champions.stages[0].rounds))}:null};}
// Used by campaign backup import as well as export. Reject oversized or broken references.
function validate(v,c,validateSheet,validateMatch){if(v==null)return null;if(typeof v!=='object'||Array.isArray(v)||Buffer.byteLength(JSON.stringify(v))>MAX_BYTES)fail('Carreira inválida no backup.');const a=structuredClone(v);if(a.version!==1||!Number.isInteger(a.rev)||a.rev<0||!Number.isInteger(a.year)||a.year<2026||a.year>2126||!a.teams||Array.isArray(a.teams)||Object.keys(a.teams).length>32||!Array.isArray(a.history)||a.history.length>100)fail('Estrutura da carreira inválida.');
 const all=new Set();for(const [id,t] of Object.entries(a.teams)){if(!/^[a-zA-Z0-9-]{16,80}$/.test(id))fail('Time inválido no backup.');const next=validateTeam(t,validateSheet,c);if(next.roster.some((p,i)=>p.id!==t.roster[i].id||all.has(p.id)))fail('Identidade de jogador inválida.');next.roster.forEach(p=>all.add(p.id));a.teams[id]=next;}
 const ref=id=>{if(typeof id!=='string'||!Object.hasOwn(a.teams,id))fail('Referência de time inválida.');};if(a.followed)ref(a.followed);
 if(a.history.length!==a.year-2026)fail('Histórico anual inconsistente.');for(let i=0;i<a.history.length;i++){const h=a.history[i];if(h.year!==2026+i||!h.names||typeof h.championsPhase!=='string'||h.championsPhase.length>60||!Array.isArray(h.leagueTable)||h.leagueTable.length>32)fail('Histórico de temporada inválido.');for(const id of [h.followed,h.leagueChampion,h.championsChampion,...Object.keys(h.names)])ref(id);for(const name of Object.values(h.names))if(typeof name!=='string'||name.length>40)fail('Nome histórico inválido.');for(const row of h.leagueTable){ref(row.id);for(const n of ['points','played','wins','draws','losses','gf','ga','gd','seed'])if(!Number.isInteger(row[n])||Math.abs(row[n])>100000)fail('Classificação histórica inválida.');}}
 if(a.season){if(a.season.year!==a.year||!a.followed)fail('Ano de competição inválido.');for(const kind of ['league','champions']){const q=a.season[kind];if(!q||q.kind!==kind||!['playing','finished'].includes(q.status)||!Array.isArray(q.stages)||q.stages.length<1||q.stages.length>5)fail('Competição inválida.');checkedIds(a,q.ids,kind==='league'?2:8,32);if(!q.ids.includes(a.followed))fail('Time acompanhado ausente.');if(kind==='champions'){if(![8,16,32].includes(q.ids.length)||!Array.isArray(q.groups)||q.groups.length!==q.ids.length/4||q.groups.some(g=>!Array.isArray(g)||g.length!==4)||new Set(q.groups.flat()).size!==q.ids.length||q.groups.flat().some(id=>!q.ids.includes(id)))fail('Grupos inválidos.');}
 const ids=new Set();for(const st of q.stages){if(!['league','groups','knockout'].includes(st.kind)||typeof st.label!=='string'||st.label.length>60||!Array.isArray(st.rounds)||st.rounds.length>62||!st.rounds.length)fail('Rodadas inválidas.');for(const games of st.rounds){if(!Array.isArray(games)||games.length>16||!games.length)fail('Jogos inválidos.');for(const g of games){if(typeof g.id!=='string'||g.id.length>80||ids.has(g.id)||g.home===g.away||!q.ids.includes(g.home)||!q.ids.includes(g.away))fail('Confronto inválido.');ids.add(g.id);if(g.score!==null&&(!Array.isArray(g.score)||g.score.length!==2||g.score.some(n=>!Number.isInteger(n)||n<0||n>99)))fail('Placar inválido.');if(g.winner!==null&&![g.home,g.away].includes(g.winner))fail('Vencedor inválido.');if(st.kind==='knockout'&&(typeof g.tie!=='string'||g.tie.length>80||![1,2].includes(g.leg)||typeof g.final!=='boolean'))fail('Chave inválida.');}}}
 if(!Number.isInteger(q.stage)||q.stage<0||q.stage>=q.stages.length||!Number.isInteger(q.round)||q.round<0||q.round>q.stages[q.stage].rounds.length)fail('Rodada atual inválida.');if(q.status==='playing'&&q.round===q.stages[q.stage].rounds.length)fail('Rodada pendente inválida.');if(q.champion!==null){ref(q.champion);if(!q.ids.includes(q.champion))fail('Campeão inválido.');}if(q.status==='finished'&&!q.champion)fail('Falta campeão.');}}
 if(a.active||a.match){if(!a.active||!a.match||!a.season||!['league','champions'].includes(a.active.competition))fail('Partida da carreira inválida.');const q=a.season[a.active.competition],g=current(q).find(g=>g.id===a.active.fixture);if(!g||g.score||![g.home,g.away].includes(a.followed))fail('Partida não corresponde ao calendário.');const entries=Object.fromEntries([g.home,g.away].flatMap(id=>a.teams[id].roster.map(p=>[p.id,{sheet:p.sheet}])));a.match=validateMatch(a.match,entries);for(const m of [a.match,a.match.undo])if(m)for(const id of [g.home,g.away])for(const p of a.teams[id].roster){if(!m.players[p.id])fail('Elenco da partida inválido.');m.players[p.id].controller=p.controller;}}
 return a;
}
module.exports={fresh,robin,table,comp,current,aggregate,record,settle,progress,finishSimulated,command,view,context,validate,RULES};
