const express = require('express');
const http = require('http');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const { Pool } = require('pg');
const { Server } = require('socket.io');
const { QUESTIONS, normalize } = require('./questions');
const { CLASH_QUESTIONS } = require('./clash_questions');
const { GAME_QUESTIONS } = require('./game_questions');
const { IMPOSTOR_WORDS } = require('./impostor_words');
const { BATTLE_QUESTIONS } = require('./battle_questions');

const app = express();
const server = http.createServer(app);
const io = new Server(server);
const PORT = process.env.PORT || 3000;
const DATA_FILE = path.join(process.env.DATA_DIR || path.join(__dirname, 'data'), 'users.json');
const db = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } }) : null;
const rooms = new Map();
const sessions = new Map();
const ADMIN_KEY = normalize('goyb');
const AVATARS = ['⚽','🦁','🐯','🐸','🐧','🦊','🐼','🐺','🦅','👾','🤖','🥷','👑','🐲'];
const CATEGORIES = { football: QUESTIONS, clash: CLASH_QUESTIONS, games: GAME_QUESTIONS, impostor: IMPOSTOR_WORDS, battle: BATTLE_QUESTIONS };
let users = {};

app.use(express.json({ limit: '30kb' }));
app.use(express.static(path.join(__dirname, 'public')));

function localLoad() { try { return JSON.parse(fs.readFileSync(DATA_FILE, 'utf8')); } catch { return {}; } }
function hash(password, salt = crypto.randomBytes(16).toString('hex')) { return { salt, hash: crypto.scryptSync(password, salt, 64).toString('hex') }; }
function equal(a, b) { const x = Buffer.from(a, 'hex'), y = Buffer.from(b, 'hex'); return x.length === y.length && crypto.timingSafeEqual(x, y); }
function publicUser(u) { return { nick:u.nick, avatar:u.avatar||'⚽', footballRecord:u.record||0, clashRecord:u.clashRecord||0, gamesQuizRecord:u.gamesQuizRecord||0, wins:u.wins||0, games:u.games||0, xp:u.xp||0, level:Math.floor((u.xp||0)/250)+1, admin:normalize(u.nick)===ADMIN_KEY }; }
function tokenFor(nick) { const token=crypto.randomBytes(32).toString('hex'); sessions.set(token,{nick,expires:Date.now()+2592e6}); return token; }
function fromToken(token='') { const s=sessions.get(token),u=s&&s.expires>Date.now()?users[normalize(s.nick)]:null; return u&&!u.disabled?u:null; }
function bearer(req) { return String(req.headers.authorization||'').replace(/^Bearer\s+/i,''); }
function auth(req,res,next) { req.user=fromToken(bearer(req)); if(!req.user)return res.status(401).json({ok:false,error:'Faça login novamente.'}); next(); }
function admin(req,res,next) { if(normalize(req.user.nick)!==ADMIN_KEY)return res.status(403).json({ok:false,error:'Acesso exclusivo do administrador.'}); next(); }

async function initStore() {
  if (!db) { users=localLoad(); return; }
  await db.query(`CREATE TABLE IF NOT EXISTS users (nickname_key TEXT PRIMARY KEY,nick TEXT NOT NULL,salt TEXT NOT NULL,password_hash TEXT NOT NULL,avatar TEXT NOT NULL DEFAULT '⚽',record INTEGER NOT NULL DEFAULT 0,wins INTEGER NOT NULL DEFAULT 0,games INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await db.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS clash_record INTEGER NOT NULL DEFAULT 0`);
  await db.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS games_quiz_record INTEGER NOT NULL DEFAULT 0`);
  await db.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS xp INTEGER NOT NULL DEFAULT 0`);
  await db.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS disabled BOOLEAN NOT NULL DEFAULT FALSE`);
  await db.query(`CREATE TABLE IF NOT EXISTS friendships (user_a TEXT NOT NULL REFERENCES users(nickname_key) ON DELETE CASCADE,user_b TEXT NOT NULL REFERENCES users(nickname_key) ON DELETE CASCADE,requested_by TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(user_a,user_b))`);
  await db.query(`CREATE TABLE IF NOT EXISTS match_history (id BIGSERIAL PRIMARY KEY,nickname_key TEXT NOT NULL REFERENCES users(nickname_key) ON DELETE CASCADE,category TEXT NOT NULL,rounds INTEGER NOT NULL,victory BOOLEAN NOT NULL,reason TEXT NOT NULL,played_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  const result=await db.query('SELECT * FROM users'); users={};
  for(const r of result.rows) users[r.nickname_key]={nick:r.nick,salt:r.salt,hash:r.password_hash,avatar:r.avatar,record:r.record,clashRecord:r.clash_record,gamesQuizRecord:r.games_quiz_record,wins:r.wins,games:r.games,xp:r.xp,disabled:r.disabled};
}
async function saveUser(key,u) {
  if(db) return db.query(`INSERT INTO users (nickname_key,nick,salt,password_hash,avatar,record,clash_record,games_quiz_record,wins,games,xp,disabled) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(nickname_key) DO UPDATE SET nick=EXCLUDED.nick,salt=EXCLUDED.salt,password_hash=EXCLUDED.password_hash,avatar=EXCLUDED.avatar,record=EXCLUDED.record,clash_record=EXCLUDED.clash_record,games_quiz_record=EXCLUDED.games_quiz_record,wins=EXCLUDED.wins,games=EXCLUDED.games,xp=EXCLUDED.xp,disabled=EXCLUDED.disabled`,[key,u.nick,u.salt,u.hash,u.avatar||'⚽',u.record||0,u.clashRecord||0,u.gamesQuizRecord||0,u.wins||0,u.games||0,u.xp||0,!!u.disabled]);
  fs.mkdirSync(path.dirname(DATA_FILE),{recursive:true}); const temp=DATA_FILE+'.tmp'; fs.writeFileSync(temp,JSON.stringify(users,null,2)); fs.renameSync(temp,DATA_FILE);
}
function achievements(u) { const a=[]; if(u.games>=1)a.push(['Primeira partida','Concluiu a primeira partida']); if(u.wins>=1)a.push(['Primeira vitória','Zerou um desafio']); if(u.games>=10)a.push(['Veterano','Jogou 10 partidas']); if(u.record>=50)a.push(['Craque','Chegou à rodada 50 no futebol']); if(u.record>=200)a.push(['Lenda do futebol','Zerou as 200 rodadas']); if(u.clashRecord>=50)a.push(['Mestre da arena','Chegou à rodada 50 no Clash Royale']); if(u.gamesQuizRecord>=25)a.push(['Enciclopédia gamer','Chegou à rodada 25 no Quiz Gamer']); return a.map(([name,description])=>({name,description})); }
function apiError(res,error){console.error(error);res.status(503).json({ok:false,error:'Não foi possível acessar os dados agora.'});}

app.post('/api/register',async(req,res)=>{try{const nick=String(req.body.nick||'').trim().slice(0,18),password=String(req.body.password||''),key=normalize(nick);if(!/^[\p{L}\p{N}_ .-]{3,18}$/u.test(nick))return res.status(400).json({ok:false,error:'Use um nickname de 3 a 18 caracteres.'});if(password.length<6||password.length>72)return res.status(400).json({ok:false,error:'A senha deve ter entre 6 e 72 caracteres.'});if(users[key])return res.status(409).json({ok:false,error:'Esse nickname já existe.'});users[key]={nick,...hash(password),avatar:'⚽',record:0,clashRecord:0,gamesQuizRecord:0,wins:0,games:0,xp:0,disabled:false};await saveUser(key,users[key]);res.json({ok:true,token:tokenFor(nick),user:publicUser(users[key])});}catch(e){apiError(res,e)}});
app.post('/api/login',(req,res)=>{const u=users[normalize(req.body.nick||'')];if(!u||u.disabled||!equal(hash(String(req.body.password||''),u.salt).hash,u.hash))return res.status(401).json({ok:false,error:'Nickname ou senha incorretos.'});res.json({ok:true,token:tokenFor(u.nick),user:publicUser(u)});});
app.get('/api/me',auth,(req,res)=>res.json({ok:true,user:publicUser(req.user),achievements:achievements(req.user)}));
app.get('/api/quiz-names',auth,(req,res)=>{const category=['football','clash','games'].includes(req.query.category)?req.query.category:'football',source=CATEGORIES[category];const names=[...new Set(source.map(q=>q.answer))].sort((a,b)=>a.localeCompare(b,'pt-BR'));res.json({ok:true,category,names});});
app.post('/api/logout',auth,(req,res)=>{sessions.delete(bearer(req));res.json({ok:true});});
app.patch('/api/profile',auth,async(req,res)=>{try{const avatar=String(req.body.avatar||'');if(!AVATARS.includes(avatar))return res.status(400).json({ok:false,error:'Avatar inválido.'});req.user.avatar=avatar;await saveUser(normalize(req.user.nick),req.user);res.json({ok:true,user:publicUser(req.user)});}catch(e){apiError(res,e)}});
app.post('/api/change-password',auth,async(req,res)=>{try{const current=String(req.body.current||''),next=String(req.body.next||'');if(!equal(hash(current,req.user.salt).hash,req.user.hash))return res.status(400).json({ok:false,error:'Senha atual incorreta.'});if(next.length<6||next.length>72)return res.status(400).json({ok:false,error:'A nova senha deve ter entre 6 e 72 caracteres.'});Object.assign(req.user,hash(next));await saveUser(normalize(req.user.nick),req.user);res.json({ok:true});}catch(e){apiError(res,e)}});
app.get('/api/leaderboard',auth,async(req,res)=>{try{const category=['football','clash','games'].includes(req.query.category)?req.query.category:'football',column=category==='clash'?'clash_record':category==='games'?'games_quiz_record':'record';if(db){const q=await db.query(`SELECT nick,avatar,${column} AS record,wins,xp FROM users WHERE disabled=FALSE ORDER BY ${column} DESC,wins DESC LIMIT 50`);return res.json({ok:true,players:q.rows.map(r=>({...r,level:Math.floor(r.xp/250)+1}))});}const value=u=>category==='clash'?u.clashRecord||0:category==='games'?u.gamesQuizRecord||0:u.record||0;const list=Object.values(users).filter(u=>!u.disabled).sort((a,b)=>value(b)-value(a)||b.wins-a.wins).slice(0,50).map(u=>({nick:u.nick,avatar:u.avatar,record:value(u),wins:u.wins,level:Math.floor((u.xp||0)/250)+1}));res.json({ok:true,players:list});}catch(e){apiError(res,e)}});
app.get('/api/history',auth,async(req,res)=>{try{if(!db)return res.json({ok:true,matches:[]});const q=await db.query('SELECT category,rounds,victory,reason,played_at FROM match_history WHERE nickname_key=$1 ORDER BY played_at DESC LIMIT 30',[normalize(req.user.nick)]);res.json({ok:true,matches:q.rows});}catch(e){apiError(res,e)}});
app.get('/api/friends',auth,async(req,res)=>{try{if(!db)return res.json({ok:true,friends:[],requests:[]});const key=normalize(req.user.nick),q=await db.query(`SELECT f.*,ua.nick AS nick_a,ua.avatar AS avatar_a,ub.nick AS nick_b,ub.avatar AS avatar_b FROM friendships f JOIN users ua ON ua.nickname_key=f.user_a JOIN users ub ON ub.nickname_key=f.user_b WHERE f.user_a=$1 OR f.user_b=$1`,[key]);const friends=[],requests=[];for(const r of q.rows){const other=r.user_a===key?{key:r.user_b,nick:r.nick_b,avatar:r.avatar_b}:{key:r.user_a,nick:r.nick_a,avatar:r.avatar_a};if(r.status==='accepted')friends.push(other);else if(r.requested_by!==key)requests.push(other);}res.json({ok:true,friends,requests});}catch(e){apiError(res,e)}});
app.post('/api/friends/request',auth,async(req,res)=>{try{if(!db)return res.status(400).json({ok:false,error:'Este recurso precisa do PostgreSQL.'});const me=normalize(req.user.nick),other=normalize(req.body.nick||'');if(!users[other]||users[other].disabled)return res.status(404).json({ok:false,error:'Usuário não encontrado.'});if(me===other)return res.status(400).json({ok:false,error:'Você não pode adicionar a si mesmo.'});const [a,b]=[me,other].sort();await db.query(`INSERT INTO friendships(user_a,user_b,requested_by,status) VALUES($1,$2,$3,'pending') ON CONFLICT(user_a,user_b) DO UPDATE SET requested_by=$3,status='pending'`,[a,b,me]);res.json({ok:true});}catch(e){apiError(res,e)}});
app.post('/api/friends/accept',auth,async(req,res)=>{try{const me=normalize(req.user.nick),other=normalize(req.body.nick||''),[a,b]=[me,other].sort();const q=await db.query(`UPDATE friendships SET status='accepted' WHERE user_a=$1 AND user_b=$2 AND requested_by<>$3`,[a,b,me]);if(!q.rowCount)return res.status(404).json({ok:false,error:'Pedido não encontrado.'});res.json({ok:true});}catch(e){apiError(res,e)}});
app.delete('/api/friends/:nick',auth,async(req,res)=>{try{const me=normalize(req.user.nick),other=normalize(req.params.nick),[a,b]=[me,other].sort();if(db)await db.query('DELETE FROM friendships WHERE user_a=$1 AND user_b=$2',[a,b]);res.json({ok:true});}catch(e){apiError(res,e)}});
app.get('/api/admin/users',auth,admin,async(req,res)=>{const list=Object.values(users).map(u=>({...publicUser(u),disabled:!!u.disabled})).sort((a,b)=>a.nick.localeCompare(b.nick));res.json({ok:true,users:list});});
app.post('/api/admin/reset-password',auth,admin,async(req,res)=>{try{const u=users[normalize(req.body.nick||'')],password=String(req.body.password||'');if(!u)return res.status(404).json({ok:false,error:'Usuário não encontrado.'});if(password.length<6||password.length>72)return res.status(400).json({ok:false,error:'Use uma senha de 6 a 72 caracteres.'});Object.assign(u,hash(password));await saveUser(normalize(u.nick),u);res.json({ok:true});}catch(e){apiError(res,e)}});
app.post('/api/admin/toggle-user',auth,admin,async(req,res)=>{try{const key=normalize(req.body.nick||''),u=users[key];if(!u)return res.status(404).json({ok:false,error:'Usuário não encontrado.'});if(key===ADMIN_KEY)return res.status(400).json({ok:false,error:'A conta administradora não pode ser suspensa.'});u.disabled=!u.disabled;await saveUser(key,u);res.json({ok:true,disabled:u.disabled});}catch(e){apiError(res,e)}});

function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=crypto.randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function makeCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let code;do{code=Array.from({length:5},()=>chars[crypto.randomInt(chars.length)]).join('');}while(rooms.has(code));return code;}
function makeDeck(category,total,difficulty){const source=CATEGORIES[category]||QUESTIONS,groups=new Map();for(const q of source){const k=category==='games'?q.id:normalize(q.answer);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(q);}const hintLimit=category==='games'?5:category==='clash'?4:difficulty==='hard'?3:difficulty==='easy'?5:4;return shuffle([...groups.values()]).slice(0,Math.min(total,groups.size)).map(v=>{const q=v[crypto.randomInt(v.length)];return{...q,hints:q.hints.slice(0,hintLimit)}});}
function active(r){return[...r.players.values()].filter(p=>p.connected);}
function replacePlayerId(r,oldId,newId){if(r.impostorId===oldId)r.impostorId=newId;if(r.clueOrder)r.clueOrder=r.clueOrder.map(id=>id===oldId?newId:id);if(r.votes){const next={};for(const [voter,target] of Object.entries(r.votes))next[voter===oldId?newId:voter]=target===oldId?newId:target;r.votes=next;}if(r.clues)r.clues.forEach(c=>{if(c.id===oldId)c.id=newId;});}
function impostorView(r,viewerId){if(r.category!=='impostor'||r.state!=='impostor')return null;const reveal=r.phase==='result',isImpostor=viewerId===r.impostorId;return{phase:r.phase,theme:r.secretCategory,currentPlayerId:r.clueOrder?.[r.clueIndex]||null,clues:r.clues||[],votesCast:Object.keys(r.votes||{}).length,hasVoted:!!r.votes?.[viewerId],result:r.impostorResult||'',role:{isImpostor,word:reveal||!isImpostor?r.secretWord:null,impostorNick:reveal?r.players.get(r.impostorId)?.nick||'Jogador secreto':null}};}
function battleView(r,viewerId){if(r.category!=='battle'||r.state!=='battle')return null;const p=r.players.get(viewerId),reveal=r.battlePhase==='result';return{phase:r.battlePhase,prompt:r.battleQuestion?.prompt||'',topic:r.battleQuestion?.topic||'',choices:r.battleChoices||[],answeredCount:[...r.players.values()].filter(x=>x.connected&&x.battleChoice).length,myChoice:p?.battleChoice||'',correctAnswer:reveal?r.battleQuestion?.answer||'':'',gained:p?.battleGained||0};}
function roomView(r,viewerId){return{code:r.code,hostId:r.hostId,state:r.state,category:r.category,config:r.config,prompt:r.question?.prompt||'',currentHint:r.currentHint,revealedHints:r.question?.hints.slice(0,r.hintIndex+1)||[],hintNumber:Math.max(0,r.hintIndex+1),totalHints:r.question?.hints.length||5,explanation:r.state==='round-result'?r.question?.explanation||'':'',roundNumber:Math.min(r.roundIndex+1,r.config.rounds),totalRounds:r.config.rounds,deadline:r.deadline,nextRoundAt:r.nextRoundAt||0,nextRoundInMs:Math.max(0,(r.nextRoundAt||0)-Date.now()),endReason:r.endReason,answer:r.answer,messages:r.messages.slice(-30),gameGuesses:(r.gameGuesses||[]).slice(-40),impostor:impostorView(r,viewerId),battle:battleView(r,viewerId),players:[...r.players.values()].map(p=>({id:p.id,nick:p.nick,avatar:p.avatar,ready:p.ready,gaveUp:p.gaveUp,connected:p.connected,correct:p.correct,score:p.score||0,streak:p.streak||0}))};}
function broadcast(r){for(const p of r.players.values())if(p.connected)io.to(p.id).emit('room:update',roomView(r,p.id));}
function reset(r){r.players.forEach(p=>{p.ready=false;p.gaveUp=false;p.guess='';p.correct=false;});}
function stopTimer(r){if(r.timer)clearTimeout(r.timer);r.timer=null;}
function setTimer(r){stopTimer(r);r.deadline=Date.now()+r.config.seconds*1000;r.timer=setTimeout(()=>finish(r,'timeout'),r.config.seconds*1000);}
function partyTimer(r,seconds,action){stopTimer(r);r.deadline=Date.now()+seconds*1000;r.timer=setTimeout(()=>{if(rooms.has(r.code)&&r.state==='impostor')action();},seconds*1000);}
function nextImpostorClue(r){r.clueIndex++;if(r.clueIndex>=r.clueOrder.length){r.phase='vote';r.votes={};partyTimer(r,60,()=>resolveImpostorVote(r));}else partyTimer(r,45,()=>{const id=r.clueOrder[r.clueIndex],p=r.players.get(id);r.clues.push({id,nick:p?.nick||'Jogador',avatar:p?.avatar||'🎭',text:'Passou a vez.'});nextImpostorClue(r);});broadcast(r);}
function finishImpostorRound(r,crewWon,text){stopTimer(r);r.phase='result';r.answer=r.secretWord;r.impostorResult=text;if(crewWon){for(const [votedBy,target] of Object.entries(r.votes||{}))if(target===r.impostorId){const p=r.players.get(votedBy);if(p)p.score=(p.score||0)+1;}}else{const imp=r.players.get(r.impostorId);if(imp)imp.score=(imp.score||0)+2;}broadcast(r);setTimeout(()=>{if(!rooms.has(r.code)||r.state!=='impostor'||r.phase!=='result')return;r.roundIndex++;startRound(r);},6500);}
function resolveImpostorVote(r){if(r.phase!=='vote')return;const tally={};for(const target of Object.values(r.votes||{}))tally[target]=(tally[target]||0)+1;const ordered=Object.entries(tally).sort((a,b)=>b[1]-a[1]),unique=ordered.length&&(!ordered[1]||ordered[0][1]>ordered[1][1]),chosen=unique?ordered[0][0]:null;if(chosen===r.impostorId){r.phase='guess';partyTimer(r,30,()=>finishImpostorRound(r,true,'O impostor foi descoberto e não acertou a palavra.'));broadcast(r);}else finishImpostorRound(r,false,chosen?'O grupo votou em uma pessoa inocente. O impostor venceu!':'A votação terminou empatada. O impostor venceu!');}
function startImpostorRound(r){if(!rooms.has(r.code))return;if(r.roundIndex>=r.config.rounds)return finish(r,'victory');const ps=active(r);if(ps.length<3)return finish(r,'not-enough-players');const item=r.deck[r.roundIndex];r.state='impostor';r.phase='clue';r.secretWord=item.word;r.secretCategory=item.category;r.answer='';r.impostorResult='';r.impostorId=ps[crypto.randomInt(ps.length)].id;r.clueOrder=shuffle(ps.map(p=>p.id));r.clueIndex=0;r.clues=[];r.votes={};reset(r);partyTimer(r,45,()=>{const id=r.clueOrder[r.clueIndex],p=r.players.get(id);r.clues.push({id,nick:p?.nick||'Jogador',avatar:p?.avatar||'🎭',text:'Passou a vez.'});nextImpostorClue(r);});broadcast(r);}
function resolveBattleRound(r){if(!rooms.has(r.code)||r.state!=='battle'||r.battlePhase!=='answer')return;stopTimer(r);r.battlePhase='result';r.nextRoundAt=Date.now()+6000;for(const p of active(r)){const correct=p.battleChoice===r.battleQuestion.answer;p.correct=correct;if(correct){const speed=Math.max(0,Math.ceil((r.deadline-(p.battleAnsweredAt||r.deadline))/1000));p.battleGained=100+speed*5+Math.min(p.streak||0,5)*20;p.score=(p.score||0)+p.battleGained;p.streak=(p.streak||0)+1;}else{p.battleGained=0;p.streak=0;}}broadcast(r);setTimeout(()=>{if(rooms.has(r.code)&&r.state==='battle'&&r.battlePhase==='result'){r.roundIndex++;startRound(r);}},6000);}
function startBattleRound(r){if(!rooms.has(r.code))return;if(r.roundIndex>=r.config.rounds)return finish(r,'victory');r.state='battle';r.battlePhase='answer';r.battleQuestion=r.deck[r.roundIndex];r.battleChoices=shuffle(r.battleQuestion.choices);r.nextRoundAt=0;r.answer='';r.players.forEach(p=>{p.battleChoice='';p.battleAnsweredAt=0;p.battleGained=0;p.correct=false;});stopTimer(r);r.deadline=Date.now()+20000;r.timer=setTimeout(()=>resolveBattleRound(r),20000);broadcast(r);}
function startRound(r){if(r.category==='impostor')return startImpostorRound(r);if(r.category==='battle')return startBattleRound(r);if(!rooms.has(r.code))return;if(r.roundIndex>=r.config.rounds)return finish(r,'victory');r.question=r.deck[r.roundIndex];r.hintIndex=r.category==='games'?-1:0;r.currentHint=r.hintIndex<0?'':r.question.hints[0];r.answer='';r.gameGuesses=[];r.nextRoundAt=0;r.state='playing';reset(r);setTimer(r);broadcast(r);}
async function saveResults(r,win){const completed=win?r.config.rounds:r.roundIndex;for(const p of r.players.values()){const key=normalize(p.nick),u=users[key];if(!u)continue;u.games=(u.games||0)+1;u.wins=(u.wins||0)+(win?1:0);u.xp=(u.xp||0)+completed+(win?50:0);if(r.category==='clash')u.clashRecord=Math.max(u.clashRecord||0,completed);else if(r.category==='games')u.gamesQuizRecord=Math.max(u.gamesQuizRecord||0,completed);else if(r.category==='football')u.record=Math.max(u.record||0,completed);await saveUser(key,u);if(db)await db.query('INSERT INTO match_history(nickname_key,category,rounds,victory,reason) VALUES($1,$2,$3,$4,$5)',[key,r.category,completed,win,r.endReason]);}}
function finish(r,reason){if(!r||!rooms.has(r.code)||['victory','defeat'].includes(r.state))return;stopTimer(r);r.state=reason==='victory'?'victory':'defeat';r.endReason=reason;r.answer=r.question?.answer||r.answer||'';saveResults(r,reason==='victory').catch(console.error);broadcast(r);}
function evaluate(r){const ps=active(r);if(!ps.length||!ps.every(p=>p.ready))return;if(ps.every(p=>p.gaveUp))return finish(r,'gave-up');const correct=ps.filter(p=>!p.gaveUp&&r.question.aliases.includes(normalize(p.guess)));if(correct.length){correct.forEach(p=>{p.correct=true;p.score=(p.score||0)+1;});stopTimer(r);r.answer=r.question.answer;r.state='round-result';const delay=r.category==='games'?10000:5000;r.nextRoundAt=Date.now()+delay;broadcast(r);setTimeout(()=>{if(rooms.has(r.code)&&r.state==='round-result'){r.roundIndex++;startRound(r);}},delay);return;}if(r.category==='games'){reset(r);broadcast(r);return;}r.hintIndex++;if(r.hintIndex>=r.question.hints.length)return finish(r,'wrong');r.currentHint=r.question.hints[r.hintIndex];reset(r);setTimer(r);broadcast(r);}

io.use((socket,next)=>{const u=fromToken(socket.handshake.auth?.token);if(!u)return next(new Error('unauthorized'));socket.data.user=u;next();});
io.on('connection',socket=>{
  const u=socket.data.user;
  socket.on('room:create',({avatar,reconnectToken,category='football',config={}}={},cb)=>{category=CATEGORIES[category]?category:'football';const max=category==='impostor'?10:category==='battle'?30:CATEGORIES[category].length,rounds=Math.max(5,Math.min(Number(config.rounds)||Math.min(200,max),max)),seconds=[30,60,90].includes(Number(config.seconds))?Number(config.seconds):60,difficulty=['easy','normal','hard'].includes(config.difficulty)?config.difficulty:'normal',code=makeCode(),token=reconnectToken||crypto.randomBytes(24).toString('hex'),p={id:socket.id,token,nick:u.nick,avatar:AVATARS.includes(avatar)?avatar:u.avatar,ready:false,gaveUp:false,guess:'',correct:false,score:0,connected:true},r={code,hostId:socket.id,players:new Map([[socket.id,p]]),state:'lobby',category,config:{rounds,seconds,difficulty},deck:[],roundIndex:0,hintIndex:0,deadline:0,timer:null,endReason:'',answer:'',messages:[]};rooms.set(code,r);socket.join(code);socket.data.roomCode=code;cb?.({ok:true,code,playerId:socket.id,reconnectToken:token});broadcast(r);});
  socket.on('room:join',({code,avatar,reconnectToken}={},cb)=>{const r=rooms.get(String(code||'').toUpperCase());if(!r)return cb?.({ok:false,error:'Sala não encontrada.'});let p=[...r.players.values()].find(x=>x.token===reconnectToken&&normalize(x.nick)===normalize(u.nick));if(p){const old=p.id,host=r.hostId===old;replacePlayerId(r,old,socket.id);r.players.delete(old);p.id=socket.id;p.connected=true;r.players.set(socket.id,p);if(host)r.hostId=socket.id;}else{if(r.state!=='lobby')return cb?.({ok:false,error:'A partida já começou.'});if(r.players.size>=10)return cb?.({ok:false,error:'Sala cheia.'});if([...r.players.values()].some(x=>normalize(x.nick)===normalize(u.nick)))return cb?.({ok:false,error:'Sua conta já está na sala.'});const token=reconnectToken||crypto.randomBytes(24).toString('hex');p={id:socket.id,token,nick:u.nick,avatar:AVATARS.includes(avatar)?avatar:u.avatar,ready:false,gaveUp:false,guess:'',correct:false,score:0,connected:true};r.players.set(socket.id,p);}socket.join(r.code);socket.data.roomCode=r.code;cb?.({ok:true,code:r.code,playerId:socket.id,reconnectToken:p.token});r.messages.push({id:crypto.randomUUID(),nick:'Sistema',text:`${u.nick} entrou na sala.`,time:Date.now()});broadcast(r);});
  socket.on('chat:send',({text}={},cb)=>{const r=rooms.get(socket.data.roomCode);text=String(text||'').trim().slice(0,180);if(!r||!text)return;r.messages.push({id:crypto.randomUUID(),nick:u.nick,avatar:u.avatar,text,time:Date.now()});if(r.messages.length>50)r.messages.shift();broadcast(r);cb?.({ok:true});});
  socket.on('game:start',cb=>{const r=rooms.get(socket.data.roomCode);if(!r)return;if(r.hostId!==socket.id)return cb?.({ok:false,error:'Apenas o dono pode começar.'});const minimum=r.category==='impostor'?3:2;if(active(r).length<minimum)return cb?.({ok:false,error:`É preciso pelo menos ${minimum} jogadores.`});r.deck=r.category==='impostor'?shuffle([...IMPOSTOR_WORDS]).slice(0,r.config.rounds):r.category==='battle'?shuffle([...BATTLE_QUESTIONS]).slice(0,r.config.rounds):makeDeck(r.category,r.config.rounds,r.config.difficulty);r.config.rounds=r.deck.length;r.roundIndex=0;r.endReason='';startRound(r);cb?.({ok:true});});
  socket.on('impostor:clue',({text}={},cb)=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id);text=String(text||'').trim().slice(0,80);if(!r||r.state!=='impostor'||r.phase!=='clue'||r.clueOrder[r.clueIndex]!==socket.id)return cb?.({ok:false,error:'Ainda não é sua vez.'});if(text.length<2)return cb?.({ok:false,error:'Escreva uma dica curta.'});r.clues.push({id:p.id,nick:p.nick,avatar:p.avatar,text});nextImpostorClue(r);cb?.({ok:true});});
  socket.on('impostor:vote',({targetId}={},cb)=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id),target=r?.players.get(targetId);if(!r||r.state!=='impostor'||r.phase!=='vote'||!p?.connected||!target?.connected||targetId===socket.id)return cb?.({ok:false,error:'Voto inválido.'});if(r.votes[socket.id])return cb?.({ok:false,error:'Você já votou.'});r.votes[socket.id]=targetId;broadcast(r);if(Object.keys(r.votes).length>=active(r).length)resolveImpostorVote(r);cb?.({ok:true});});
  socket.on('impostor:guess',({guess}={},cb)=>{const r=rooms.get(socket.data.roomCode);guess=String(guess||'').trim().slice(0,60);if(!r||r.state!=='impostor'||r.phase!=='guess'||r.impostorId!==socket.id)return cb?.({ok:false,error:'Apenas o impostor pode responder.'});if(!guess)return cb?.({ok:false,error:'Digite a palavra secreta.'});const correct=normalize(guess)===normalize(r.secretWord);finishImpostorRound(r,!correct,correct?'O impostor descobriu a palavra e venceu!':'O impostor errou a palavra. A tripulação venceu!');cb?.({ok:true,correct});});
  socket.on('hint:request',cb=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id);if(!r||r.category!=='games'||r.state!=='playing'||!p?.connected)return cb?.({ok:false,error:'A dica não está disponível agora.'});if(r.hintIndex>=r.question.hints.length-1)return cb?.({ok:false,error:'As cinco dicas já foram usadas.'});r.hintIndex++;r.currentHint=r.question.hints[r.hintIndex];broadcast(r);cb?.({ok:true});});
  socket.on('games:guess',({guess}={},cb)=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id);guess=String(guess||'').trim().slice(0,80);if(!r||r.category!=='games'||r.state!=='playing'||!p?.connected)return cb?.({ok:false,error:'Não é possível responder agora.'});if(!guess)return cb?.({ok:false,error:'Digite uma resposta.'});const correct=r.question.aliases.includes(normalize(guess));r.gameGuesses=r.gameGuesses||[];r.gameGuesses.push({id:crypto.randomUUID(),playerId:p.id,nick:p.nick,avatar:p.avatar,text:guess,correct,time:Date.now()});if(r.gameGuesses.length>40)r.gameGuesses.shift();if(correct){p.correct=true;p.score=(p.score||0)+1;stopTimer(r);r.answer=r.question.answer;r.state='round-result';r.nextRoundAt=Date.now()+10000;broadcast(r);setTimeout(()=>{if(rooms.has(r.code)&&r.state==='round-result'){r.roundIndex++;startRound(r);}},10000);}else broadcast(r);cb?.({ok:true,correct});});
  socket.on('battle:answer',({choice}={},cb)=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id);choice=String(choice||'');if(!r||r.category!=='battle'||r.state!=='battle'||r.battlePhase!=='answer'||!p?.connected)return cb?.({ok:false,error:'Não é possível responder agora.'});if(p.battleChoice)return cb?.({ok:false,error:'Sua resposta já foi confirmada.'});if(!r.battleChoices.includes(choice))return cb?.({ok:false,error:'Escolha uma das alternativas.'});p.battleChoice=choice;p.battleAnsweredAt=Date.now();broadcast(r);if(active(r).every(x=>x.battleChoice))resolveBattleRound(r);cb?.({ok:true});});
  socket.on('guess:ready',({guess}={},cb)=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id);guess=String(guess||'').trim().slice(0,60);if(!r||r.state!=='playing'||!p)return;if(r.category==='games')return cb?.({ok:false,error:'Use o chat de palpites do Quiz Gamer.'});if(!guess)return cb?.({ok:false,error:'Digite um palpite.'});p.guess=guess;p.ready=true;p.gaveUp=false;broadcast(r);evaluate(r);cb?.({ok:true});});
  socket.on('guess:cancel',()=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id);if(r?.state==='playing'&&p){p.ready=false;p.gaveUp=false;p.guess='';broadcast(r);}});
  socket.on('guess:giveup',cb=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id);if(!r||r.state!=='playing'||!p)return;p.gaveUp=true;p.ready=true;p.guess='';broadcast(r);evaluate(r);cb?.({ok:true});});
  socket.on('game:restart',cb=>{const r=rooms.get(socket.data.roomCode);if(!r||r.hostId!==socket.id)return cb?.({ok:false,error:'Apenas o dono pode jogar novamente.'});r.state='lobby';r.roundIndex=0;r.deck=[];r.endReason='';r.players.forEach(p=>{p.score=0;p.streak=0;p.battleChoice='';});reset(r);broadcast(r);cb?.({ok:true});});
  socket.on('room:leave',()=>socket.disconnect(true));
  socket.on('disconnect',()=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id);if(!r||!p)return;p.connected=false;p.ready=false;r.messages.push({id:crypto.randomUUID(),nick:'Sistema',text:`${p.nick} desconectou.`,time:Date.now()});if(r.hostId===socket.id){const next=active(r)[0];if(next)r.hostId=next.id;}broadcast(r);setTimeout(()=>{if(!rooms.has(r.code)||p.connected)return;r.players.delete(p.id);if(!r.players.size){stopTimer(r);rooms.delete(r.code);}else broadcast(r);},120000);});
});

initStore().then(()=>server.listen(PORT,()=>console.log(`Grupão Minigames em http://localhost:${PORT} (${db?'PostgreSQL':'arquivo local'})`))).catch(error=>{console.error('Não foi possível conectar ao banco de dados:',error);process.exit(1);});
