'use strict';

// Personagens de ficção reconhecíveis, com preferência por coadjuvantes.
// A obra só aparece para quem pode ver o personagem. Nunca enviar este banco ao cliente.
const rows = [
  ['Perry, o Ornitorrinco', 'Phineas e Ferb', ['Perry', 'Perry o Ornitorrinco', 'Agente P']],
  ['Dr. Heinz Doofenshmirtz', 'Phineas e Ferb', ['Doofenshmirtz', 'Heinz Doofenshmirtz', 'Dr Doofenshmirtz']],
  ['Candace Flynn', 'Phineas e Ferb', ['Candace']],
  ['Isabella Garcia-Shapiro', 'Phineas e Ferb', ['Isabella', 'Isabella Garcia Shapiro']],
  ['Waddles', 'Gravity Falls', ['Gingado']],
  ['Bill Cipher', 'Gravity Falls', ['Bill']],
  ['Soos Ramirez', 'Gravity Falls', ['Soos']],
  ['Stan Pines', 'Gravity Falls', ['Tio Stan', 'Stanley Pines', 'Stanley', 'Stan']],
  ['Wendy Corduroy', 'Gravity Falls', ['Wendy']],
  ['Rei Gelado', 'Hora de Aventura', ['Simon Petrikov', 'Rei do Gelo', 'Ice King', 'Simon']],
  ['Marceline', 'Hora de Aventura', ['Marceline Abadeer']],
  ['Princesa Caroço', 'Hora de Aventura', ['Lumpy Space Princess']],
  ['BMO', 'Hora de Aventura', ['Beemo']],
  ['Lemongrab', 'Hora de Aventura', ['Conde de Lemongrab']],
  ['Saltitão', 'Apenas um Show', ['Skips']],
  ['Benson', 'Apenas um Show', []],
  ['Pairulito', 'Apenas um Show', ['Pops']],
  ['Musculoso', 'Apenas um Show', ['Muscle Man']],
  ['Nicole Watterson', 'O Incrível Mundo de Gumball', ['Nicole']],
  ['Ricardo Watterson', 'O Incrível Mundo de Gumball', ['Ricardo', 'Richard Watterson', 'Richard']],
  ['Anais Watterson', 'O Incrível Mundo de Gumball', ['Anais']],
  ['Darwin Watterson', 'O Incrível Mundo de Gumball', ['Darwin']],
  ['Lula Molusco', 'Bob Esponja', ['Squidward', 'Lula']],
  ['Sandy Bochechas', 'Bob Esponja', ['Sandy', 'Sandy Cheeks']],
  ['Plankton', 'Bob Esponja', ['Sheldon Plankton']],
  ['Gary', 'Bob Esponja', ['Gary o Caracol']],
  ['Sr. Siriguejo', 'Bob Esponja', ['Seu Siriguejo', 'Siriguejo', 'Senhor Siriguejo', 'Mr Krabs']],
  ['Karen', 'Bob Esponja', []],
  ['Cosmo', 'Os Padrinhos Mágicos', []],
  ['Wanda', 'Os Padrinhos Mágicos', []],
  ['Denzel Crocker', 'Os Padrinhos Mágicos', ['Crocker', 'Sr Crocker', 'Professor Crocker']],
  ['Jorgen Von Strangle', 'Os Padrinhos Mágicos', ['Jorgen']],
  ['Gir', 'Invasor Zim', []],
  ['Vovô Max', 'Ben 10', ['Max Tennyson', 'Max']],
  ['Kevin Levin', 'Ben 10', ['Kevin', 'Kevin 11']],
  ['Vilgax', 'Ben 10', []],
  ['Ravena', 'Os Jovens Titãs', ['Raven']],
  ['Estelar', 'Os Jovens Titãs', ['Starfire', 'Koriandr']],
  ['Mutano', 'Os Jovens Titãs', ['Beast Boy', 'Garfield Logan']],
  ['Mojo Jojo', 'As Meninas Superpoderosas', ['Macaco Louco']],
  ['Ele', 'As Meninas Superpoderosas', ['Him']],
  ['Mandark', 'O Laboratório de Dexter', []],
  ['Dee Dee', 'O Laboratório de Dexter', ['Deedee', 'Didi']],
  ['Eustácio', 'Coragem, o Cão Covarde', ['Eustace', 'Eustacio Bagge']],
  ['Muriel', 'Coragem, o Cão Covarde', ['Muriel Bagge']],
  ['Queixo Rubro', 'Os Padrinhos Mágicos', ['Crimson Chin']],
  ['Zé Colmeia', 'Zé Colmeia', ['Yogi Bear', 'Zé Colméia']],
  ['Catatau', 'Zé Colmeia', ['Boo Boo']],
  ['Manda-Chuva', 'Manda-Chuva', ['Manda Chuva', 'Top Cat']],
  ['Penélope Charmosa', 'Corrida Maluca', ['Penelope Pitstop']],
  ['Dick Vigarista', 'Corrida Maluca', ['Dick Dastardly']],
  ['Muttley', 'Corrida Maluca', ['Mutley']],
  ['Marvin, o Marciano', 'Looney Tunes', ['Marvin', 'Marvin o Marciano']],
  ['Ligeirinho', 'Looney Tunes', ['Speedy Gonzales']],
  ['Wile E. Coyote', 'Looney Tunes', ['Coiote', 'Wile E Coyote']],
  ['Frajola', 'Looney Tunes', ['Sylvester']],
  ['Ned Flanders', 'Os Simpsons', ['Ned', 'Flanders']],
  ['Sr. Burns', 'Os Simpsons', ['Senhor Burns', 'Burns', 'Montgomery Burns', 'Charles Montgomery Burns']],
  ['Krusty', 'Os Simpsons', ['Krusty o Palhaço']],
  ['Milhouse Van Houten', 'Os Simpsons', ['Milhouse']],
  ['Sideshow Bob', 'Os Simpsons', ['Bob', 'Robert Terwilliger']],
  ['Zoidberg', 'Futurama', ['Dr Zoidberg', 'John Zoidberg']],
  ['Bender', 'Futurama', ['Bender Rodriguez']],
  ['Roger', 'American Dad!', ['Roger Smith']],
  ['Stewie Griffin', 'Uma Família da Pesada', ['Stewie']],
  ['Eric Cartman', 'South Park', ['Cartman']],
  ['Kenny McCormick', 'South Park', ['Kenny']],
  ['Sr. Cabeça de Batata', 'Toy Story', ['Senhor Cabeça de Batata', 'Cabeça de Batata', 'Mr Potato Head']],
  ['Rex', 'Toy Story', []],
  ['Slinky', 'Toy Story', ['Slinky Dog']],
  ['Lotso', 'Toy Story 3', []],
  ['Edna Moda', 'Os Incríveis', ['Edna', 'Edna Mode']],
  ['Gelado', 'Os Incríveis', ['Frozone', 'Lucius Best']],
  ['Síndrome', 'Os Incríveis', ['Syndrome', 'Buddy Pine']],
  ['Roz', 'Monstros S.A.', []],
  ['Randall Boggs', 'Monstros S.A.', ['Randall']],
  ['Boo', 'Monstros S.A.', []],
  ['Bruce', 'Procurando Nemo', ['Bruce o Tubarão']],
  ['Crush', 'Procurando Nemo', []],
  ['Dug', 'Up: Altas Aventuras', []],
  ['Kevin', 'Up: Altas Aventuras', ['Kevin a Ave']],
  ['Anton Ego', 'Ratatouille', ['Ego']],
  ['Luigi', 'Carros', []],
  ['Mate', 'Carros', ['Tow Mater', 'Mater']],
  ['Bing Bong', 'Divertida Mente', []],
  ['Heihei', 'Moana', ['Hei Hei']],
  ['Tamatoa', 'Moana', []],
  ['Mushu', 'Mulan', []],
  ['Kronk', 'A Nova Onda do Imperador', []],
  ['Yzma', 'A Nova Onda do Imperador', []],
  ['Hades', 'Hércules', []],
  ['Timon', 'O Rei Leão', ['Timão']],
  ['Rafiki', 'O Rei Leão', []],
  ['Zazu', 'O Rei Leão', []],
  ['Sebastião', 'A Pequena Sereia', ['Sebastian']],
  ['Lumière', 'A Bela e a Fera', ['Lumiere']],
  ['Madame Samovar', 'A Bela e a Fera', ['Mrs Potts', 'Samovar']],
  ['Gato de Cheshire', 'Alice no País das Maravilhas', ['Gato Risonho', 'Cheshire']],
  ['Grilo Falante', 'Pinóquio', ['Jiminy Cricket']],
  ['Abu', 'Aladdin', []],
  ['Iago', 'Aladdin', []],
  ['Capitão Gancho', 'Peter Pan', ['Gancho', 'Captain Hook']],
  ['Olaf', 'Frozen', []],
  ['Kristoff', 'Frozen', []],
  ['Bruno Madrigal', 'Encanto', ['Bruno']],
  ['Baymax', 'Operação Big Hero', []],
  ['Breu', 'A Origem dos Guardiões', ['Pitch Black', 'Pitch']],
  ['Lorde Farquaad', 'Shrek', ['Farquaad', 'Lord Farquaad']],
  ['Biscoito', 'Shrek', ['Gingy', 'Homem Biscoito']],
  ['Príncipe Encantado', 'Shrek', ['Prince Charming']],
  ['Rei Julien', 'Madagascar', ['Julien', 'Rei Julian', 'King Julien']],
  ['Mort', 'Madagascar', []],
  ['Capitão', 'Madagascar', ['Skipper']],
  ['Recruta', 'Madagascar', ['Private']],
  ['Mestre Shifu', 'Kung Fu Panda', ['Shifu']],
  ['Mestre Oogway', 'Kung Fu Panda', ['Oogway']],
  ['Tai Lung', 'Kung Fu Panda', []],
  ['Astrid Hofferson', 'Como Treinar o Seu Dragão', ['Astrid']],
  ['Scrat', 'A Era do Gelo', []],
  ['Buck', 'A Era do Gelo', ['Buck Wild']],
  ['Sid', 'A Era do Gelo', []],
  ['Vector', 'Meu Malvado Favorito', ['Vetor', 'Victor Perkins']],
  ['Dr. Nefário', 'Meu Malvado Favorito', ['Nefário', 'Doutor Nefário', 'Dr Nefario']],
  ['Coraline Jones', 'Coraline', ['Coraline']],
  ['Oogie Boogie', 'O Estranho Mundo de Jack', []],
  ['Sally', 'O Estranho Mundo de Jack', []],
  ['Totoro', 'Meu Amigo Totoro', []],
  ['Sem-Rosto', 'A Viagem de Chihiro', ['Sem Rosto', 'Kaonashi', 'No Face']],
  ['Calcifer', 'O Castelo Animado', []],
  ['Jiji', 'O Serviço de Entregas da Kiki', []],
  ['Psyduck', 'Pokémon', []],
  ['Meowth', 'Pokémon', ['Miau']],
  ['Wobbuffet', 'Pokémon', []],
  ['Snorlax', 'Pokémon', []],
  ['Jigglypuff', 'Pokémon', []],
  ['Brock', 'Pokémon', ['Takeshi']],
  ['Jessie', 'Pokémon', ['Musashi']],
  ['Mestre Kame', 'Dragon Ball', ['Kame', 'Master Roshi', 'Roshi']],
  ['Mr. Satan', 'Dragon Ball', ['Mr Satan', 'Hercule', 'Hércules']],
  ['Majin Boo', 'Dragon Ball', ['Majin Buu', 'Buu', 'Majin Bu']],
  ['Kuririn', 'Dragon Ball', ['Krillin']],
  ['Yamcha', 'Dragon Ball', []],
  ['Piccolo', 'Dragon Ball', ['Picollo']],
  ['Gaara', 'Naruto', []],
  ['Rock Lee', 'Naruto', ['Lee']],
  ['Shikamaru Nara', 'Naruto', ['Shikamaru']],
  ['Jiraiya', 'Naruto', ['Jiraya']],
  ['Orochimaru', 'Naruto', []],
  ['Tony Tony Chopper', 'One Piece', ['Chopper', 'Tony Chopper']],
  ['Brook', 'One Piece', []],
  ['Usopp', 'One Piece', ['Sogeking']],
  ['Buggy', 'One Piece', ['Buggy o Palhaço']],
  ['Bon Clay', 'One Piece', ['Bentham', 'Mr 2']],
  ['Ryuk', 'Death Note', []],
  ['L', 'Death Note', ['L Lawliet', 'Lawliet']],
  ['Alphonse Elric', 'Fullmetal Alchemist', ['Alphonse']],
  ['Armstrong', 'Fullmetal Alchemist', ['Alex Louis Armstrong', 'Alex Armstrong']],
  ['Happy', 'Fairy Tail', []],
  ['Kon', 'Bleach', []],
  ['Hiei', 'Yu Yu Hakusho', []],
  ['Kuwabara', 'Yu Yu Hakusho', ['Kazuma Kuwabara']],
  ['Dobby', 'Harry Potter', []],
  ['Luna Lovegood', 'Harry Potter', ['Luna']],
  ['Rúbeo Hagrid', 'Harry Potter', ['Hagrid', 'Rubeus Hagrid']],
  ['Minerva McGonagall', 'Harry Potter', ['McGonagall', 'Minerva']],
  ['Gollum', 'O Senhor dos Anéis', ['Smeagol', 'Sméagol']],
  ['Gimli', 'O Senhor dos Anéis', []],
  ['Chewbacca', 'Star Wars', ['Chewie', 'Chewbaca']],
  ['C-3PO', 'Star Wars', ['C3PO']],
  ['Jabba', 'Star Wars', ['Jabba the Hutt', 'Jabba o Hutt']],
  ['Drax', 'Guardiões da Galáxia', ['Drax o Destruidor']],
  ['Yondu', 'Guardiões da Galáxia', ['Yondu Udonta']],
  ['Rocket Raccoon', 'Guardiões da Galáxia', ['Rocket']],
  ['Wong', 'Doutor Estranho', []],
  ['Mística', 'X-Men', ['Mystique', 'Raven Darkholme']],
  ['Noturno', 'X-Men', ['Nightcrawler', 'Kurt Wagner']],
  ['Pinguim', 'Batman', ['Oswald Cobblepot', 'Penguin']],
  ['Charada', 'Batman', ['Riddler', 'Edward Nigma', 'Edward Nashton']],
  ['Alfred Pennyworth', 'Batman', ['Alfred']],
  ['Davy Jones', 'Piratas do Caribe', ['Davey Jones']],
  ['Hector Barbossa', 'Piratas do Caribe', ['Barbossa', 'Capitão Barbossa']],
  ['Doc Brown', 'De Volta para o Futuro', ['Emmett Brown', 'Doutor Brown', 'Dr Brown']],
  ['Gizmo', 'Gremlins', []],
  ['Sloth', 'Os Goonies', []],
  ['Mãozinha', 'A Família Addams', ['Thing']],
  ['Tio Fester', 'A Família Addams', ['Fester', 'Tio Chico']],
  ['Zordon', 'Power Rangers', []],
  ['Dustin Henderson', 'Stranger Things', ['Dustin']],
  ['Dwight Schrute', 'The Office', ['Dwight']],
  ['Chandler Bing', 'Friends', ['Chandler']],
  ['Saul Goodman', 'Breaking Bad / Better Call Saul', ['Jimmy McGill', 'Saul']],
  ['Waluigi', 'Super Mario', []],
  ['Rei Boo', 'Super Mario', ['King Boo']],
  ['Toadette', 'Super Mario', []],
  ['Bowser Jr.', 'Super Mario', ['Bowser Jr', 'Bowser Junior']],
  ['Dr. Eggman', 'Sonic', ['Eggman', 'Dr Robotnik', 'Robotnik', 'Ivo Robotnik']],
  ['Knuckles', 'Sonic', ['Knuckles the Echidna']],
  ['Tingle', 'The Legend of Zelda', []],
  ['Chun-Li', 'Street Fighter', ['Chun Li', 'Chunli']],
  ['Scorpion', 'Mortal Kombat', ['Hanzo Hasashi']],
];

const canonical = value => String(value || '').normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]/g, '');
const WHO_CHARACTERS = rows.map(([name, universe, aliases], index) => ({
  id: `who-${index + 1}`, name, universe,
  aliases: [...new Set([name, ...aliases].map(canonical))],
}));
module.exports = { WHO_CHARACTERS, canonical };
