'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto'),fs=require('fs'),os=require('os'),path=require('path');
const {createBot,createReaders,mountInteractions,mountBotAdmin,COMMANDS}=require('../discord_bot');
const keys=crypto.generateKeyPairSync('ed25519'),publicKey=keys.publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('hex');
const env={DISCORD_APPLICATION_ID:'123456789012345678',DISCORD_GUILD_ID:'223456789012345678',DISCORD_PUBLIC_KEY:publicKey,DISCORD_BOT_TOKEN:'FAKE_TOKEN_NEVER_REAL',PUBLIC_SITE_URL:'https://grupao.alwaysdata.net'};
let serial=323456789012345678n;
function interaction(name='site',options=[]){return {id:String(serial++),type:2,application_id:env.DISCORD_APPLICATION_ID,guild_id:env.DISCORD_GUILD_ID,token:'fake_interaction_token',member:{user:{id:'423456789012345678'}},data:{type:1,name,options}};}
async function harness(options={}){const express=require('express'),app=express(),calls=[];const bot=mountInteractions({app,express,env,readers:{latest:async()=>null,ranking:async()=>[]},fetchImpl:async(url,opts)=>{calls.push({url,opts});return {ok:true,json:async()=>({id:env.DISCORD_APPLICATION_ID})};},...options});app.use(express.json());mountBotAdmin({app,bot,auth:(req,res,next)=>req.headers['x-user']?next():res.sendStatus(401),admin:(req,res,next)=>req.headers['x-user']==='goyb'?next():res.sendStatus(403)});const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});const base='http://127.0.0.1:'+server.address().port;
 return {bot,calls,base,async send(body,{timestamp=String(Math.floor(Date.now()/1000)),signature,raw}={}){const text=raw??JSON.stringify(body);signature??=crypto.sign(null,Buffer.from(timestamp+text),keys.privateKey).toString('hex');return fetch(base+'/api/discord/interactions',{method:'POST',headers:{'content-type':'application/json','X-Signature-Ed25519':signature,'X-Signature-Timestamp':timestamp},body:text});},close:()=>new Promise(r=>server.close(r))};}
async function until(fn){for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}assert.fail('tempo de espera esgotado');}
test('PING assinado funciona; assinatura inválida, corpo alterado e replay antigo são recusados',async()=>{const h=await harness();try{assert.deepEqual(await(await h.send({type:1})).json(),{type:1});assert.equal((await h.send({type:1},{signature:'0'.repeat(128)})).status,401);const original=JSON.stringify({type:1}),timestamp=String(Math.floor(Date.now()/1000)),signature=crypto.sign(null,Buffer.from(timestamp+original),keys.privateKey).toString('hex');assert.equal((await h.send({type:1},{timestamp,signature,raw:'{ "type": 1 }'})).status,401);assert.equal((await h.send({type:1},{timestamp:String(Math.floor(Date.now()/1000)-600)})).status,401);assert.equal((await h.send(null,{raw:'invalid'})).status,400);assert.equal(h.calls.length,0);}finally{await h.close();}});
test('site responde sem consultar dados; outro servidor e outra aplicação são bloqueados',async()=>{let reads=0;const h=await harness({readers:{latest:async()=>reads++,ranking:async()=>reads++}});try{const data=await(await h.send(interaction())).json();assert.equal(data.type,4);assert.ok(data.data.content.includes(env.PUBLIC_SITE_URL));assert.deepEqual(data.data.allowed_mentions,{parse:[]});const wrong=interaction();wrong.guild_id='523456789012345678';assert.equal((await(await h.send(wrong)).json()).data.flags,64);wrong.application_id='623456789012345678';assert.equal((await h.send(wrong)).status,400);assert.equal(reads,0);}finally{await h.close();}});
test('ranking confirma antes do banco, atualiza resposta original e deduplica interação',async()=>{let release,reads=0;const h=await harness({readers:{ranking:()=>{reads++;return new Promise(r=>release=r);}}});try{const input=interaction('ranking',[{name:'jogo',type:3,value:'clash'}]);assert.equal((await(await h.send(input)).json()).type,5);assert.equal((await(await h.send(input)).json()).type,5);assert.equal(h.calls.length,0);release([{nick:'nome_* @everyone',record:200,wins:10,salt:'SECRET',hash:'SECRET'}]);await until(()=>h.calls.length===1);const out=JSON.parse(h.calls[0].opts.body);assert.ok(out.embeds[0].title.includes('Clash Royale'));assert.ok(out.embeds[0].description.includes('200 rodadas'));assert.ok(!h.calls[0].opts.body.includes('SECRET'));assert.deepEqual(out.allowed_mentions,{parse:[]});assert.ok(h.calls[0].url.endsWith('/messages/@original'));assert.equal(h.calls[0].opts.method,'PATCH');assert.equal(reads,1);}finally{await h.close();}});
test('novidades usa anúncio confirmado; cache compartilha consulta entre usuários',async()=>{let reads=0;const h=await harness({readers:{latest:async()=>{reads++;return {version:'4.8.16',title:'Novidades',news:'Online',fixes:'Correções',attempt:'PRIVATE'};}}});try{await h.send(interaction('novidades'));const b=interaction('novidades');b.member.user.id='723456789012345678';await h.send(b);await until(()=>h.calls.length===2);assert.equal(reads,1);assert.ok(h.calls[0].opts.body.includes('4.8.16'));assert.ok(!h.calls[0].opts.body.includes('PRIVATE'));}finally{await h.close();}});
test('falha e timeout no banco recebem resposta amigável sem expor erro privado',async()=>{const h=await harness({workTimeoutMs:20,readers:{latest:async()=>{throw Error('DATABASE_URL=SECRET');},ranking:()=>new Promise(()=>{})}});try{await h.send(interaction('novidades'));const b=interaction('ranking');b.member.user.id='723456789012345678';await h.send(b);await until(()=>h.calls.length===2);assert.ok(h.calls.every(c=>c.opts.body.includes('Não consegui consultar')));assert.ok(h.calls.every(c=>!c.opts.body.includes('SECRET')));}finally{await h.close();}});
test('limite por usuário e opção inválida não disparam trabalho',async()=>{const h=await harness();try{await h.send(interaction('site'));assert.equal((await(await h.send(interaction('ranking'))).json()).data.flags,64);const b=interaction('ranking',[{name:'jogo',type:3,value:'SQL'}]);b.member.user.id='723456789012345678';assert.equal((await(await h.send(b)).json()).data.flags,64);assert.equal(h.calls.length,0);}finally{await h.close();}});
test('leitor local usa recorde correto, desempata e exclui suspensos sem dados privados',async()=>{const readers=createReaders({getUsers:()=>({a:{nick:'Ana',record:10,clashRecord:30,gamesQuizRecord:40,wins:2,hash:'SECRET'},b:{nick:'Bia',record:10,wins:3},c:{nick:'Suspenso',record:500,disabled:true}})});assert.deepEqual((await readers.ranking('football')).map(x=>x.nick),['Bia','Ana']);assert.equal((await readers.ranking('clash'))[0].record,30);assert.equal((await readers.ranking('games'))[0].record,40);assert.ok(!JSON.stringify(await readers.ranking('games')).includes('SECRET'));await assert.rejects(readers.ranking('invalid'));});
test('último anúncio confirmado é encontrado mesmo após 30 falhas',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'discord-latest-'));try{const all={old:{version:'4.8.16',status:'sent',updatedAt:'2026-01-01'}};for(let i=0;i<35;i++)all['failed'+i]={status:'failed',updatedAt:'2026-02-01'};fs.writeFileSync(path.join(dir,'discord-updates.json'),JSON.stringify(all));assert.equal((await require('../discord_updates').createStore({dataDir:dir}).latestSent()).version,'4.8.16');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('registro faz upsert de apenas três comandos após conferir identidade do token',async()=>{const calls=[],bot=createBot({env,readers:{},fetchImpl:async(url,opts)=>{calls.push({url,opts});return {ok:true,json:async()=>({id:env.DISCORD_APPLICATION_ID})};}});const result=await bot.register();assert.deepEqual(result.commands,['site','novidades','ranking']);assert.equal(calls.length,4);assert.ok(calls.slice(1).every(c=>c.opts.method==='POST'&&c.url.includes('/guilds/'+env.DISCORD_GUILD_ID+'/commands')));assert.deepEqual(calls.slice(1).map(c=>JSON.parse(c.opts.body)),COMMANDS);assert.ok(!JSON.stringify(bot.info()).includes(env.DISCORD_BOT_TOKEN));await assert.rejects(bot.register(),e=>e.status===429);
 const wrong=createBot({env,readers:{},fetchImpl:async()=>({ok:true,json:async()=>({id:'999'})})});await assert.rejects(wrong.register(),/outra aplicação/);
});
test('configuração ausente não derruba servidor; APIs do painel exigem administrador',async()=>{const h=await harness({env:{}});try{assert.equal((await h.send({type:1})).status,503);for(const [suffix,opts] of [['',{}],['/register',{method:'POST',headers:{'content-type':'application/json'},body:'{"confirm":true}'}]]){assert.equal((await fetch(h.base+'/api/admin/discord-bot'+suffix,opts)).status,401);assert.equal((await fetch(h.base+'/api/admin/discord-bot'+suffix,{...opts,headers:{...opts.headers,'x-user':'amigo'}})).status,403);}const data=await(await fetch(h.base+'/api/admin/discord-bot',{headers:{'x-user':'goyb'}})).json();assert.equal(data.configured,false);assert.equal(data.canRegister,false);}finally{await h.close();}});
