'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const {configuration,preview,createStore,createUpdates,mountUpdates}=require('../discord_updates');
const env={DISCORD_UPDATES_WEBHOOK_URL:'https://discord.com/api/webhooks/123456789012345678/EXAMPLE_TOKEN_NOT_REAL_1234567890',PUBLIC_SITE_URL:'https://grupao.alwaysdata.net'};
const input={version:'v4.8.15',title:'Novidades',news:'Participantes online',fixes:'Correções no campo'};
function context(fetchImpl){const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'discord-test-')),store=createStore({dataDir}),service=createUpdates({dataDir,env,fetchImpl,store});return {dataDir,store,service,payload:()=>({...input,confirm:true,previewHash:service.preview(input).hash}),close:()=>fs.rmSync(dataDir,{recursive:true,force:true})};}
test('configuração restringe destino do webhook e prévia limita textos e menções',()=>{
 assert.equal(configuration(env).configured,true);for(const url of ['http://discord.com/api/webhooks/123456789012345678/EXAMPLE_TOKEN_NOT_REAL_1234567890',env.DISCORD_UPDATES_WEBHOOK_URL.replace('discord.com','discord.com.attacker.test'),env.DISCORD_UPDATES_WEBHOOK_URL+'?anything=1','https://user:pass@discord.com/api/webhooks/123456789012345678/EXAMPLE_TOKEN_NOT_REAL_1234567890'])assert.equal(configuration({...env,DISCORD_UPDATES_WEBHOOK_URL:url}).configured,false);
 const p=preview({...input,news:'@everyone <script>x</script>'},env.PUBLIC_SITE_URL);assert.deepEqual(p.payload.allowed_mentions,{parse:[]});assert.equal(p.announcement.version,'4.8.15');assert.throws(()=>preview({...input,news:'x'.repeat(1001)},env.PUBLIC_SITE_URL));assert.throws(()=>preview({...input,version:'__proto__'},env.PUBLIC_SITE_URL));assert.throws(()=>preview({...input,news:'',fixes:''},env.PUBLIC_SITE_URL));
});
test('prévia não envia; confirmação e conteúdo da prévia são exigidos',async()=>{
 let calls=0;const c=context(async()=>{calls++;return {ok:true,json:async()=>({id:'123'})};});try{c.service.preview(input);assert.equal(calls,0);await assert.rejects(c.service.publish(input));await assert.rejects(c.service.publish({...c.payload(),news:'mudou'}));assert.equal(calls,0);}finally{c.close();}
});
test('envio único persiste antes da rede, bloqueia concorrência e repetição após reinício',async()=>{
 let release,calls=0;const c=context(async(url,opts)=>{calls++;assert.ok(url.endsWith('?wait=true'));assert.equal(opts.redirect,'error');assert.equal((await c.store.list())[0].status,'pending');await new Promise(r=>release=r);return {ok:true,json:async()=>({id:'1234567890'})};});
 try{const first=c.service.publish(c.payload());while(!release)await new Promise(r=>setImmediate(r));await assert.rejects(c.service.publish(c.payload()),e=>e.status===409);release();assert.equal((await first).record.status,'sent');const again=createUpdates({dataDir:c.dataDir,env,fetchImpl:async()=>{calls++;}});await assert.rejects(again.publish(c.payload()),e=>e.status===409);assert.equal(calls,1);}finally{c.close();}
});
test('timeout e respostas ambíguas não reenviam nem expõem URL secreta',async()=>{
 const c=context(async()=>{throw Error(env.DISCORD_UPDATES_WEBHOOK_URL);});try{const result=await c.service.publish(c.payload());assert.equal(result.record.status,'uncertain');assert.ok(!JSON.stringify(await c.service.info()).includes('EXAMPLE_TOKEN'));await assert.rejects(c.service.publish(c.payload()),e=>e.status===409);await assert.rejects(c.service.resolve({version:'4.8.15',attempt:result.record.attempt,status:'failed',confirm:true}),e=>e.status===409);
 const file=path.join(c.dataDir,'discord-updates.json'),data=JSON.parse(fs.readFileSync(file));data['4.8.15'].startedAt-=130000;fs.writeFileSync(file,JSON.stringify(data));await c.service.resolve({version:'4.8.15',attempt:result.record.attempt,status:'failed',confirm:true});assert.equal((await c.store.list())[0].status,'failed');}finally{c.close();}
});
test('recusa explícita permite nova tentativa; rate limit impede envio imediato',async()=>{
 let calls=0;const c=context(async()=>{calls++;return calls===1?{ok:false,status:400}:{ok:true,json:async()=>({id:'123'})};});try{assert.equal((await c.service.publish(c.payload())).record.status,'failed');assert.equal((await c.service.publish(c.payload())).record.status,'sent');}finally{c.close();}
 const rate=context(async()=>({ok:false,status:429,json:async()=>({retry_after:30})}));try{const result=await rate.service.publish(rate.payload());assert.equal(result.record.status,'failed');assert.ok(result.record.retryAt>Date.now());await assert.rejects(rate.service.publish(rate.payload()),e=>e.status===409);}finally{rate.close();}
});
test('registro corrompido ou falha ao confirmar envio bloqueiam repetição insegura',async()=>{
 let calls=0;const c=context(async()=>{calls++;return {ok:true,json:async()=>({id:'123'})};});try{fs.writeFileSync(path.join(c.dataDir,'discord-updates.json'),'INVALID');await assert.rejects(c.service.publish(c.payload()));assert.equal(calls,0);fs.unlinkSync(path.join(c.dataDir,'discord-updates.json'));const store={...c.store,finish:async()=>{throw Error('disk');}},s=createUpdates({env,dataDir:c.dataDir,store,fetchImpl:async()=>{calls++;return {ok:true,json:async()=>({id:'123'})};}});await assert.rejects(s.publish(c.payload()));assert.equal((await c.store.list())[0].status,'pending');await assert.rejects(c.service.publish(c.payload()));assert.equal(calls,1);}finally{c.close();}
});
test('API exige administrador em todas as rotas e não devolve credencial',async()=>{
 const express=require('express'),c=context(async()=>({ok:true,json:async()=>({id:'123'})})),app=express();app.use(express.json());mountUpdates({app,env,dataDir:c.dataDir,fetchImpl:async()=>({ok:true,json:async()=>({id:'123'})}),auth:(req,res,next)=>req.headers['x-user']?next():res.sendStatus(401),admin:(req,res,next)=>req.headers['x-user']==='goyb'?next():res.sendStatus(403)});const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});try{const base=`http://127.0.0.1:${server.address().port}/api/admin/discord-updates`;for(const route of ['', '/preview','/publish','/resolve']){const opts=route?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(c.payload())}:{};assert.equal((await fetch(base+route,opts)).status,401);assert.equal((await fetch(base+route,{...opts,headers:{...opts.headers,'x-user':'jogador'}})).status,403);}const response=await fetch(base,{headers:{'x-user':'goyb'}});assert.equal(response.status,200);assert.ok(!(await response.text()).includes('EXAMPLE_TOKEN'));}finally{await new Promise(r=>server.close(r));c.close();}
});
