'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),express=require('express');
const {createRpg,validateSheet,attributes,styles}=require('../rpg'),game=require('../rpg_match'),{createBackupTools,hash}=require('../rpg_backup');
const backup=createBackupTools({validateSheet,attributes,styles,normalize:s=>s.toLowerCase()});
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
function fixture(freeMode=true){
 const c={id:'ORIGINAL',name:'Campanha',owner:'mestre',updatedAt:new Date().toISOString(),notes:'Diário importante',members:{mestre:{nick:'Mestre',sheet:null},amigo:{nick:'Amigo',sheet:null}},extras:{},savedTeams:{}};
 for(let i=0;i<14;i++){const keeper=i%7===0;const sheet=validateSheet({name:'Atleta '+i,age:18,height:180,nationality:'Brasil',position:keeper?'Goleiro':'Atacante',style:keeper?'Muralha':'Matador',ego:'Rival',level:3,base:Object.fromEntries(attributes(keeper).map(a=>[a,12])),growth:{Físico:4},approved:true,photo:i===0?png:'',talents:'Talento',weapon:'Arma',notes:'História'},{},true);c.extras['npc:'+i]={nick:sheet.name,sheet,rolls:null};}
 const ids=Object.keys(c.extras),teams=[0,1].map(t=>({name:'Time '+t,color:'#123456',formation:'2-3-1',ids:ids.slice(t*7,t*7+7)}));
 c.savedTeams.aaaaaaaaaaaaaaaa={id:'aaaaaaaaaaaaaaaa',...teams[0],rev:1};game.command(c,'mestre',{op:'create',teams,freeMode},s=>s);c.match.pins=[{id:'pin',x:30,y:20,by:'amigo'}];return c;
}
async function context(fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'backup-test-')),c=fixture();fs.writeFileSync(path.join(dir,'rpg-campaigns.json'),JSON.stringify({ORIGINAL:c}));let server,url;
 async function boot(){const app=express(),r=createRpg({app,express,db:null,dataDir:dir,normalize:s=>s.toLowerCase(),auth:(req,res,next)=>{req.user={nick:req.headers['x-user']||'mestre'};next();}});await r.init();await new Promise(r=>server=app.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${server.address().port}/api/rpg`;}
 async function req(route,body,user='mestre'){const res=await fetch(url+route,{method:body?'POST':'GET',headers:{'content-type':'application/json','x-user':user},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json()};}
 try{await boot();await fn({req,c,restart:async()=>{await new Promise(r=>server.close(r));await boot();}});}finally{if(server)await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}
}
test('backup preserva fichas, fotos, times e pausa apenas a cópia',()=>{const c=fixture();c.match.status='playing';c.match.running=true;c.match.anchor=Date.now()-5000;const original=structuredClone(c),f=backup.pack(c,'mestre');assert.deepEqual(c,original);assert.equal(f.campaign.match.status,'paused');assert.ok(f.campaign.match.elapsed>=5000);assert.equal(f.campaign.extras['npc:0'].sheet.photo,png);assert.deepEqual(f.campaign.savedTeams,c.savedTeams);assert.equal(backup.parse(f,'mestre').campaign.notes,c.notes);});
test('backup valida integridade, versão, permissões e referências',()=>{const f=backup.pack(fixture(),'mestre');assert.throws(()=>backup.parse(f,'amigo'),{status:403});for(const change of [x=>x.version=99,x=>x.campaign.notes='alterado',x=>{x.campaign.match.ball.holder='ausente';x.checksum=hash(x.campaign);},x=>{x.campaign.extras['npc:0'].sheet.age=12;x.checksum=hash(x.campaign);}]){const x=structuredClone(f);change(x);assert.throws(()=>backup.parse(x,'mestre'),{status:400});}});
test('backup conserva lance automático pendente e desfazer',()=>{const c=fixture(false);game.command(c,'mestre',{op:'resume',matchId:c.match.id,rev:c.match.rev},s=>s);game.command(c,'mestre',{op:'declare',matchId:c.match.id,rev:c.match.rev,actor:c.match.ball.holder,kind:'shoot'},s=>s);const f=backup.pack(c,'mestre'),r=backup.restore(backup.parse(f,'mestre'),'mestre','Cópia','aaaaaaaaaaaaaaaa');assert.deepEqual(r.match.pending,c.match.pending);assert.ok(r.match.undo);assert.equal(r.match.undo.id,r.match.id);assert.equal(r.match.status,'paused');});
test('API exporta apenas para mestre e prévia não cria save',()=>context(async({req})=>{assert.equal((await req('/campaigns/ORIGINAL/backup',null,'amigo')).status,403);assert.equal((await req('/campaigns/ORIGINAL/backup',null,'intruso')).status,403);const f=(await req('/campaigns/ORIGINAL/backup')).data;const p=await req('/backups/preview',{file:f});assert.equal(p.status,200);assert.equal(p.data.sheets,14);assert.equal(p.data.photos,1);assert.equal((await req('/campaigns')).data.campaigns.length,1);assert.equal((await req('/backups/preview',{file:f},'amigo')).status,403);}));
test('restauração concorrente cria uma cópia, preserva original e persiste após reiniciar',()=>context(async({req,restart})=>{const f=(await req('/campaigns/ORIGINAL/backup')).data,b={file:f,name:'Restaurado',requestId:'aaaaaaaaaaaaaaaa',expectedChecksum:f.checksum,confirm:true};const rs=await Promise.all([req('/backups/restore',b),req('/backups/restore',b)]);assert.deepEqual(rs[0],rs[1]);assert.equal(rs[0].status,200);const id=rs[0].data.id;assert.notEqual(id,'ORIGINAL');await restart();const r=(await req('/campaigns/'+id)).data;assert.equal(r.notes,f.campaign.notes);assert.deepEqual(r.extras,f.campaign.extras);assert.deepEqual(r.savedTeams,f.campaign.savedTeams);assert.deepEqual(r.match.pins,f.campaign.match.pins);assert.notEqual(r.match.id,f.campaign.match.id);assert.equal((await req('/campaigns')).data.campaigns.length,2);assert.equal((await req('/campaigns/ORIGINAL')).data.name,'Campanha');assert.equal((await req('/campaigns/'+id,null,'amigo')).status,200);f.campaign.notes='Outro';f.checksum=hash(f.campaign);assert.equal((await req('/backups/restore',{...b,file:f,expectedChecksum:f.checksum})).status,409);}));
test('restauração exige confirmação e a prévia do mesmo arquivo',()=>context(async({req})=>{const f=(await req('/campaigns/ORIGINAL/backup')).data,b={file:f,name:'Restaurado',requestId:'bbbbbbbbbbbbbbbb',expectedChecksum:f.checksum};assert.equal((await req('/backups/restore',b)).status,400);assert.equal((await req('/backups/restore',{...b,confirm:true,expectedChecksum:'outro'})).status,409);assert.equal((await req('/campaigns')).data.campaigns.length,1);}));
test('backup maior que limite de ficha é aceito nas rotas de restauração',()=>context(async({req})=>{const f=(await req('/campaigns/ORIGINAL/backup')).data;for(let i=0;i<200;i++)f.campaign.match.log.push({id:'registro'+i,at:Date.now(),message:'Anotação',details:'x'.repeat(9000)});f.campaign.match.log=f.campaign.match.log.slice(-200);f.checksum=hash(f.campaign);assert.ok(Buffer.byteLength(JSON.stringify(f))>1500*1024);assert.equal((await req('/backups/preview',{file:f})).status,200);assert.equal((await req('/backups/restore',{file:f,name:'Grande',requestId:'cccccccccccccccc',expectedChecksum:f.checksum,confirm:true})).status,200);}));
