'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto'),express=require('express');
const rpg=require('../rpg'),career=require('../rpg_career'),engine=require('../rpg_match'),{seed}=require('../scripts/test-local');
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'match-store-'));try{seed(dir);const c=JSON.parse(fs.readFileSync(path.join(dir,'rpg-campaigns.json'))).CARREIRA2026;const a=c.career,g=career.current(a.season.league).find(g=>[g.home,g.away].includes(a.followed));career.command(c,'goyb',{op:'open',rev:a.rev,competition:'league',fixture:g.id},{validateSheet:rpg.validateSheet,currentSheet:s=>rpg.validateSheet(s,{},true)});c.match=structuredClone(a.match);c.match.id=crypto.randomUUID();c.members.amigo={nick:'amigo',sheet:null};const actor=Object.keys(a.match.players)[0];a.match.players[actor].controller='amigo';c.members.goyb.sheet={photo:'x'.repeat(1024*1024)};c.sheetTrash=[{photo:'y'.repeat(1024*1024)}];return {c,actor};}finally{fs.rmSync(dir,{recursive:true,force:true});}}
// Transaction double measures payload boundaries, commit ordering and route behavior.
// It does not emulate PostgreSQL's JSONB implementation or network latency.
function database(c){let data=structuredClone(c),peak=0,active=0;const writes=[];
return {get data(){return data;},writes,get peak(){return peak;},get active(){return active;},connect:async()=>{active++;peak=Math.max(peak,active);let draft;return {query:async(sql,args)=>{await new Promise(r=>setTimeout(r,1));if(sql==='BEGIN')draft=structuredClone(data);if(sql.startsWith('SELECT')){assert.ok(sql.includes('FOR UPDATE'));assert.ok(sql.includes('jsonb_object_agg'));const isCareer=sql.includes("data->'career'->'match'");return {rows:[{owner:draft.owner,members:Object.fromEntries(Object.entries(draft.members).map(([id,m])=>[id,{nick:m.nick}])),match:structuredClone(isCareer?draft.career.match:draft.match),...(isCareer?{active:structuredClone(draft.career.active)}:{})}]};}if(sql.startsWith('UPDATE')){const isCareer=sql.includes("'{career,match}'");writes.push({scope:isCareer?'career':'friendly',body:args[1]});if(isCareer)draft.career.match=JSON.parse(args[1]);else draft.match=JSON.parse(args[1]);draft.updatedAt=args[2];}if(sql==='COMMIT')data=draft;return {rows:[]};},release:()=>{active--;}};}};}
async function context(fn){const {c,actor}=fixture(),db=database(c),app=express();rpg.createRpg({app,express,db,dataDir:os.tmpdir(),normalize:s=>s,auth:(req,res,next)=>{req.user={nick:req.headers['x-user']||'goyb'};next();}});const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});const send=async(scope,input,user='goyb')=>{const r=await fetch(`http://127.0.0.1:${server.address().port}/api/rpg/campaigns/${c.id}/${scope==='career'?'career/':''}match`,{method:'POST',headers:{'content-type':'application/json','x-user':user},body:JSON.stringify(input)});return {status:r.status,body:await r.json()};};try{await fn({db,actor,send,c});}finally{await new Promise(r=>server.close(r));}}
test('rotas PostgreSQL: 12 rolagens concorrentes nos dois campos não alteram calendário, fichas ou histórico anual',()=>context(async({db,send,c})=>{const previous=structuredClone(c.career);delete previous.match;const results=await Promise.all(Array.from({length:12},(_,i)=>{const scope=i%2?'career':'friendly';return send(scope,{op:'dice',matchId:scope==='career'?c.career.match.id:c.match.id,requestId:crypto.randomUUID(),count:1,sides:20,mode:'sum',bonus:0});}));assert.ok(results.every(r=>r.status===200));const next=structuredClone(db.data.career);delete next.match;assert.deepEqual(next,previous);assert.equal(db.data.match.log.filter(x=>x.roll).length,6);assert.equal(db.data.career.match.log.filter(x=>x.roll).length,6);assert.equal(db.data.members.goyb.sheet.photo.length,1024*1024);assert.deepEqual(db.data.sheetTrash,c.sheetTrash);assert.equal(db.peak,1);assert.equal(db.active,0);assert.ok(db.writes.every(w=>!w.body.includes('photo')&&!w.body.includes('season')));console.log('Partidas reais do motor: 12 ações, '+db.writes.reduce((n,w)=>n+Buffer.byteLength(w.body),0)+' bytes enviados ao banco; fichas/fotos fora da carga de gravação.');}));
test('rota otimizada mantém permissões, controle, revisão e deduplicação de dados da carreira',()=>context(async({db,send,c,actor})=>{const m=c.career.match,requestId=crypto.randomUUID(),dice={op:'dice',matchId:m.id,requestId,count:1,sides:20,mode:'sum',bonus:0,actor};assert.equal((await send('career',dice,'intruso')).status,403);assert.equal((await send('career',dice,'amigo')).status,200);assert.equal((await send('career',dice,'amigo')).status,200);assert.equal(db.data.career.match.log.filter(x=>x.roll).length,1);const other=Object.keys(m.players).find(id=>id!==actor);assert.equal((await send('career',{...dice,actor:other,requestId:crypto.randomUUID()},'amigo')).status,403);assert.equal((await send('career',{op:'finish',matchId:m.id,rev:m.rev})).status,409);const fresh=db.data.career.match;assert.equal((await send('career',{op:'finish',matchId:fresh.id,rev:fresh.rev})).status,200);assert.equal(db.data.career.match.status,'finished');assert.equal(db.data.match.status,c.match.status);assert.equal((await send('career',{op:'create'})).status,400);assert.equal(db.active,0);}));
test('campo da carreira confirmado por outra aba rejeita ações atrasadas sem recriar partida',()=>context(async({db,send,c})=>{db.data.career.match=null;db.data.career.active=null;assert.equal((await send('career',{op:'dice',matchId:c.career.match.id,requestId:crypto.randomUUID(),count:1,sides:20,mode:'sum',bonus:0})).status,404);assert.equal(db.data.career.match,null);assert.equal(db.writes.length,0);assert.equal(db.active,0);}));
