'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {point,fromClient,distance,format,createMeasure}=require('../public/rpg_ruler');
test('régua: campo completo mede 105 por 68 m e diagonal euclidiana',()=>{assert.equal(distance(point(0,0),point(105,0)),105);assert.equal(distance(point(0,0),point(0,68)),68);assert.equal(distance(point(0,0),point(3,4)),5);assert.equal(distance(point(0,0),point(105,68)),Math.hypot(105,68));assert.equal(format(44.44),'44,4 m');});
test('régua: escala independente do tamanho visual e da posição da tela',()=>{for(const width of [560,840,1400]){const rect={left:100,top:50,width,height:width*68/105},a=fromClient(100,50,rect),b=fromClient(100+width/2,50+rect.height/2,rect);assert.deepEqual(a,{x:0,y:0});assert.ok(Math.abs(b.x-52.5)<1e-8);assert.ok(Math.abs(b.y-34)<1e-8);}});
test('régua: arrastar fora do campo limita a medição à borda',()=>{assert.deepEqual(fromClient(-10,500,{left:0,top:0,width:105,height:68}),{x:0,y:68});assert.throws(()=>point(NaN,3));assert.throws(()=>fromClient(1,1,{left:0,top:0,width:0,height:1}));});
test('régua: arrastar mede e mantém o resultado ao soltar',()=>{const m=createMeasure();m.begin({x:10,y:10});m.move({x:13,y:14});assert.equal(m.state.meters,5);m.finish(true);assert.equal(m.state.phase,'done');assert.equal(m.state.meters,5);m.begin({x:90,y:30});assert.deepEqual(m.state.a,{x:90,y:30});assert.equal(m.state.meters,0);});
test('régua: dois toques fixam origem e destino sem mover a origem',()=>{const m=createMeasure();m.begin({x:1,y:1});m.finish(false);assert.equal(m.state.phase,'waiting');m.move({x:15,y:20});m.begin({x:4,y:5});m.finish(false);assert.deepEqual(m.state.a,{x:1,y:1});assert.equal(m.state.meters,5);assert.equal(m.state.phase,'done');});
test('régua: limpar remove a medida sem modificar coordenadas fornecidas',()=>{const m=createMeasure(),a={x:5,y:10},b={x:9,y:13};m.begin(a);m.move(b);m.finish(true);const s=m.state;s.a.x=99;assert.equal(m.state.a.x,5);m.clear();assert.deepEqual(m.state,{a:null,b:null,phase:'empty',meters:0});assert.deepEqual(a,{x:5,y:10});assert.deepEqual(b,{x:9,y:13});});
