'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{token}=require('../rpg_sync'),{createPolicy}=require('../public/rpg_poll');
test('token detecta comandos, troca de partida, restart e fim de tempo sem depender de consultas',()=>{const m={id:'M',rev:1,status:'playing',half:1,elapsed:899000,anchor:1000,running:true};assert.equal(token(m,1100),token(m,1500));assert.notEqual(token(m,1500),token(m,2000));for(const change of [{rev:2},{id:'N'},{status:'paused'},{restarted:true}])assert.notEqual(token(m,1100),token({...m,...change},1100));assert.equal(token(null),'empty');assert.equal(token({...m,pending:true},1500),token({...m,pending:true},2000));});
test('consulta desacelera sem mudanças e erros, retomando rapidez após alteração',()=>{const p=createPolicy();assert.equal(p.delay,1200);for(let i=0;i<8;i++)p.result(true);assert.equal(p.delay,5000);p.result(false);assert.equal(p.delay,1200);for(let i=0;i<20;i++)p.failed();assert.equal(p.delay,30000);p.reset();assert.equal(p.delay,1200);});
test('API responde pequeno sem alterações, protege acesso e retorna dados novos',async()=>{
 const express=require('express'),fs=require('fs'),os=require('os'),path=require('path'),{createRpg}=require('../rpg');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sync-test-'));const c={id:'C',owner:'mestre',members:{mestre:{nick:'mestre'}},match:{id:'M',rev:1,status:'paused',half:1,elapsed:0,anchor:1,running:false,log:Array.from({length:200},(_,i)=>({message:'Registro do jogo '.repeat(15),id:i})),players:{},undo:null}};fs.writeFileSync(path.join(dir,'rpg-campaigns.json'),JSON.stringify({C:c}));const app=express(),r=createRpg({app,express,db:null,dataDir:dir,normalize:v=>v,auth:(req,res,next)=>{req.user={nick:req.headers['x-user']||'mestre'};next();}});await r.init();const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
 try{const url=`http://127.0.0.1:${server.address().port}/api/rpg/campaigns/C/match`,first=await(await fetch(url)).json(),second=await(await fetch(url+'?since='+first.sync)).json();assert.equal(second.unchanged,true);assert.equal(second.match,undefined);assert.ok(JSON.stringify(second).length<JSON.stringify(first).length/100);assert.equal((await fetch(url+'?since='+first.sync,{headers:{'x-user':'intruso'}})).status,403);assert.ok((await(await fetch(url+'?since=antigo')).json()).match);console.log('Resposta de teste: completa='+Buffer.byteLength(JSON.stringify(first))+' bytes; sem alterações='+Buffer.byteLength(JSON.stringify(second))+' bytes');}
 finally{await new Promise(resolve=>server.close(resolve));fs.rmSync(dir,{recursive:true,force:true});}
});
