'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {command}=require('../rpg_match');
function fixture(){return {owner:'mestre',members:{mestre:{nick:'Mestre'},amigo:{nick:'Amigo'},outro:{nick:'Outro'}},match:{id:'M',rev:1,freeMode:true,status:'playing',running:true,elapsed:100,anchor:Date.now(),half:1,players:{a:{id:'a',name:'A',controller:'amigo',team:0,x:10,y:10,mods:{Passe:4}},b:{id:'b',name:'B',controller:'outro',team:1,x:90,y:60,mods:{Passe:2}}},ball:{holder:'a',x:10,y:10},score:[0,0],log:[],pending:null}};}
function send(c,k,op,data={}){command(c,k,{matchId:c.match.id,rev:c.match.rev,op,...data},s=>s);}
const roll={count:2,sides:20,bonus:3,mode:'highest',requestId:'aaaaaaaaaaaaaaaa',actor:'a',attribute:'Passe'};
test('mesa livre: movimento amplo sem dados, mesmo pausada, com controle por jogador',()=>{const c=fixture();send(c,'amigo','freeMove',{actor:'a',positionRev:0,to:{x:100,y:60}});assert.equal(c.match.players.a.x,100);assert.equal(c.match.ball.x,100);assert.equal(c.match.pending,null);assert.equal(c.match.running,true);assert.throws(()=>send(c,'outro','freeMove',{actor:'a',positionRev:1,to:{x:1,y:1}}),/controla/);c.match.status='paused';send(c,'amigo','freeMove',{actor:'a',positionRev:1,to:{x:1,y:1}});assert.throws(()=>send(c,'amigo','freeMove',{actor:'a',positionRev:2,to:{x:106,y:1}}));});
test('movimentos de peças diferentes aceitam mesma revisão; mesma peça rejeita comando antigo',()=>{const c=fixture(),old=c.match.rev;send(c,'amigo','freeMove',{rev:old,actor:'a',positionRev:0,to:{x:40,y:20}});send(c,'outro','freeMove',{rev:old,actor:'b',positionRev:0,to:{x:80,y:20}});assert.throws(()=>send(c,'amigo','freeMove',{actor:'a',positionRev:0,to:{x:1,y:1}}),/peça mudou/);assert.equal(c.match.players.b.x,80);});
test('somente mestre move a bola ou atribui posse; movimento antigo é rejeitado',()=>{const c=fixture();assert.throws(()=>send(c,'amigo','freeBall',{positionRev:0,to:{x:2,y:2}}),/mestre/);send(c,'mestre','freeBall',{positionRev:0,to:{x:50,y:34}});assert.equal(c.match.ball.holder,null);assert.throws(()=>send(c,'mestre','freeBall',{positionRev:0,actor:'b'}),/bola mudou/);send(c,'mestre','freeBall',{positionRev:1,actor:'b'});assert.equal(c.match.ball.holder,'b');});
test('dados independentes não alteram relógio, campo, placar, posse ou lance pendente',()=>{const c=fixture();c.match.pending={id:'antigo',phase:'reaction'};const before=structuredClone(c.match);send(c,'mestre','dice',{...roll,dice:[5,12]});for(const k of ['players','ball','score','pending','elapsed','anchor','running','status'])assert.deepEqual(c.match[k],before[k]);assert.equal(c.match.log.at(-1).total,19);send(c,'mestre','dice',{...roll,dice:[20,20]});assert.equal(c.match.log.length,1);});
test('dados validam identidade, limites e registro externo exclusivo do mestre',()=>{const c=fixture();assert.throws(()=>send(c,'outro','dice',roll),/controla/);assert.throws(()=>send(c,'amigo','dice',{...roll,dice:[1,2]}),/mestre/);assert.throws(()=>send(c,'mestre','dice',{...roll,dice:[21,2]}));assert.throws(()=>send(c,'amigo','dice',{...roll,count:99}));assert.throws(()=>send(c,'amigo','dice',{...roll,attribute:'inexistente'}));send(c,'amigo','dice',roll);assert.equal(c.match.log[0].dice.length,2);assert.ok(c.match.log[0].dice.every(n=>n>=1&&n<=20));});
test('ativar mesa livre preserva partida antiga e cancela apenas o lance pendente',()=>{const c=fixture();delete c.match.freeMode;c.match.pending={id:'velho'};const before=structuredClone(c.match);assert.throws(()=>send(c,'amigo','enableFree'),/mestre/);send(c,'mestre','enableFree');assert.equal(c.match.freeMode,true);assert.equal(c.match.status,'paused');assert.equal(c.match.pending,null);assert.deepEqual(c.match.players,before.players);assert.deepEqual(c.match.score,before.score);assert.deepEqual(c.match.ball,before.ball);assert.throws(()=>send(c,'amigo','declare',{actor:'a',kind:'run'}),/mesa livre/);});
test('desfazer movimento mantém histórico e deduplicação de rolagens',()=>{const c=fixture();send(c,'amigo','freeMove',{actor:'a',positionRev:0,to:{x:60,y:20}});send(c,'mestre','dice',{...roll,dice:[3,8]});send(c,'mestre','undo');assert.equal(c.match.players.a.x,10);send(c,'mestre','dice',{...roll,dice:[20,20]});assert.equal(c.match.log.filter(l=>l.roll).length,1);});
test('desfazer não reutiliza revisão de peça ou bola',()=>{const c=fixture();send(c,'amigo','freeMove',{actor:'a',positionRev:0,to:{x:60,y:20}});const rev=c.match.players.a.moveRev;send(c,'mestre','undo');assert.throws(()=>send(c,'amigo','freeMove',{actor:'a',positionRev:rev,to:{x:99,y:20}}),/peça mudou/);assert.throws(()=>send(c,'mestre','freeBall',{positionRev:0,to:{x:99,y:20}}),/bola mudou/);});
test('API: mesa livre salva movimentos e dados, protege acesso e retoma após reinício',async()=>{
 const express=require('express'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{createRpg}=require('../rpg');
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tabletop-api-')),c=fixture();c.id='C';fs.writeFileSync(path.join(dir,'rpg-campaigns.json'),JSON.stringify({C:c}));let server,url;
 async function boot(){const app=express(),r=createRpg({app,express,db:null,dataDir:dir,normalize:v=>v,auth:(req,res,next)=>{req.user={nick:req.headers['x-user']};next();}});await r.init();await new Promise(resolve=>{server=app.listen(0,'127.0.0.1',resolve);});url=`http://127.0.0.1:${server.address().port}/api/rpg/campaigns/C/match`;}
 async function req(user,body){const res=await fetch(url,{method:body?'POST':'GET',headers:{'x-user':user,'content-type':'application/json'},body:body?JSON.stringify({matchId:'M',...body}):undefined});return {status:res.status,data:await res.json()};}
 try{await boot();assert.equal((await req('intruso')).status,403);let results=await Promise.all([req('amigo',{op:'freeMove',actor:'a',positionRev:0,to:{x:50,y:10}}),req('outro',{op:'freeMove',actor:'b',positionRev:0,to:{x:55,y:15}})]);assert.ok(results.every(r=>r.status===200));results=await Promise.all([req('amigo',{op:'dice',...roll}),req('amigo',{op:'dice',...roll})]);assert.ok(results.every(r=>r.status===200));let m=(await req('amigo')).data.match;assert.equal(m.log.filter(l=>l.roll).length,1);assert.equal(m.players.a.x,50);assert.equal(m.players.b.x,55);assert.equal((await req('outro',{op:'freeMove',actor:'a',positionRev:1,to:{x:1,y:1}})).status,403);await new Promise(r=>server.close(r));await boot();m=(await req('amigo')).data.match;assert.equal(m.freeMode,true);assert.equal(m.status,'paused');assert.equal(m.players.a.x,50);assert.equal(m.log.filter(l=>l.roll).length,1);assert.equal((await req('amigo',{op:'dice',...roll})).data.match.log.filter(l=>l.roll).length,1);}
 finally{if(server)await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}
});
