'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {command,publicMatch,wins,HALF}=require('../rpg_match');
const attrs=['Carisma','Físico','Frieza','Ritmo','Passe','Finalização','Bola Parada','Defesa','Domínio','Drible','Interceptação','Reflexo','Reação','Saída','Posicionamento'];
function fixture(){const c={owner:'mestre',members:{mestre:{},amigo:{}},extras:{}};const teams=[0,1].map(t=>{const ids=Array.from({length:7},(_,i)=>`npc:${t}_${i}`);ids.forEach((id,i)=>c.extras[id]={sheet:{name:id,approved:true,position:i?'Atacante':'Goleiro',style:i?'Matador':'Líbero',stats:Object.fromEntries(attrs.map(a=>[a,{modifier:2}]))}});return {name:'Time '+t,color:t?'#ffad52':'#46e4ff',formation:'2-3-1',ids};});command(c,'mestre',{op:'create',teams},s=>s);return c;}
function cmd(c,op,body={},k='mestre'){command(c,k,{op,matchId:c.match.id,rev:c.match.rev,actionId:c.match.pending?.id,...body},s=>s);}
function resume(c){cmd(c,'resume');}
function pos(c,id,x,y){cmd(c,'position',{actor:id,to:{x,y},reason:'Cenário de teste'});}
function roll(c,id,dice){cmd(c,'roll',{actor:id,dice});}
function dice(c,id,n){return Array(1+Math.abs(c.match.pending.tests.find(t=>t.player===id).advantage)).fill(n);}
test('7x7 válido, um goleiro, sem fichas duplicadas, jogadores autorizados',()=>{const c=fixture();assert.equal(Object.keys(c.match.players).length,14);assert.equal(c.match.status,'setup');assert.throws(()=>cmd(c,'resume',{},'amigo'),/mestre/);resume(c);assert.throws(()=>cmd(c,'declare',{actor:'npc:0_1',kind:'run',to:{x:50,y:30}},'amigo'),/controla/);assert.throws(()=>cmd(c,'declare',{actor:'npc:0_1',kind:'run',to:{x:106,y:30}}));assert.throws(()=>command({...c,match:null},'mestre',{op:'create',teams:[{name:'a',color:'#ffffff',formation:'2-3-1',ids:Array(7).fill('npc:0_1')},{name:'b',color:'#ffffff',formation:'2-3-1',ids:Array(7).fill('npc:1_1')}]},s=>s));});
test('passe simples troca posse sem dados; somente uma ação por vez',()=>{const c=fixture();pos(c,'npc:0_1',20,20);pos(c,'npc:0_2',25,40);resume(c);cmd(c,'declare',{actor:'npc:0_1',kind:'pass',target:'npc:0_2'});assert.throws(()=>cmd(c,'declare',{actor:'npc:0_2',kind:'run',to:{x:30,y:30}}));cmd(c,'advance');assert.equal(c.match.ball.holder,'npc:0_2');assert.equal(c.match.pending,null);});
test('interceptação recupera posse; rolagem duplicada rejeitada',()=>{const c=fixture();pos(c,'npc:0_1',20,20);pos(c,'npc:0_2',25,40);pos(c,'npc:1_1',22,30);resume(c);cmd(c,'declare',{actor:'npc:0_1',kind:'pass',target:'npc:0_2'});cmd(c,'react',{actor:'npc:1_1',response:'intercept'});assert.equal(c.match.running,false);roll(c,'npc:0_1',[5]);assert.throws(()=>roll(c,'npc:0_1',[20]),/já foi feita/);roll(c,'npc:1_1',[15]);assert.equal(c.match.ball.holder,'npc:1_1');assert.equal(c.match.running,true);});
test('gol soma uma vez e desfazer recupera placar, posse e posições',()=>{const c=fixture();pos(c,'npc:0_1',95,34);pos(c,'npc:1_1',50,10);resume(c);cmd(c,'declare',{actor:'npc:0_1',kind:'shoot',mode:'normal'});cmd(c,'advance');const aid=c.match.pending.id;roll(c,'npc:0_1',dice(c,'npc:0_1',20));roll(c,'npc:1_0',[1]);assert.equal(c.match.score[0],1);assert.equal(c.match.players['npc:0_1'].goals,1);assert.equal(c.match.status,'paused');assert.throws(()=>cmd(c,'roll',{actor:'npc:1_0',actionId:aid,dice:[1]}));cmd(c,'undo');assert.equal(c.match.score[0],0);assert.equal(c.match.ball.holder,'npc:0_1');assert.equal(c.match.players['npc:0_1'].x,95);assert.equal(c.match.status,'paused');assert.match(c.match.log.at(-1).message,/desfez/);});
test('defesa por até três pontos gera rebote; fora disso segura',()=>{const c=fixture();pos(c,'npc:0_1',95,34);pos(c,'npc:1_1',94,35);resume(c);cmd(c,'declare',{actor:'npc:0_1',kind:'shoot'});cmd(c,'advance');roll(c,'npc:0_1',dice(c,'npc:0_1',10));roll(c,'npc:1_0',[12]);assert.equal(c.match.rebound,'npc:0_1');assert.equal(c.match.players['npc:1_0'].saves,1);cmd(c,'declare',{actor:'npc:0_1',kind:'shoot'});cmd(c,'advance');assert.equal(c.match.pending.tests[0].advantage,1);assert.equal(c.match.pending.tests[1].attribute,'Reação');roll(c,'npc:0_1',[3,4]);roll(c,'npc:1_0',[18]);assert.equal(c.match.ball.holder,'npc:1_0');});
test('corrida usa Ritmo em dobro e mantém bola junto da peça',()=>{const c=fixture();pos(c,'npc:0_1',30,34);resume(c);cmd(c,'declare',{actor:'npc:0_1',kind:'run',to:{x:60,y:34}});cmd(c,'advance');roll(c,'npc:0_1',[10]);assert.equal(c.match.players['npc:0_1'].x,44);assert.equal(c.match.ball.x,44);});
test('desarme vence só acima; empate preserva ataque',()=>{const c=fixture();pos(c,'npc:0_1',50,34);pos(c,'npc:1_1',52,34);resume(c);cmd(c,'declare',{actor:'npc:1_1',kind:'tackle'});cmd(c,'advance');roll(c,'npc:1_1',[10]);roll(c,'npc:0_1',[10]);assert.equal(c.match.ball.holder,'npc:0_1');});
test('reação fora da trajetória e jogador do mesmo time rejeitados',()=>{const c=fixture();pos(c,'npc:0_1',10,10);pos(c,'npc:0_2',20,10);pos(c,'npc:1_1',80,60);resume(c);cmd(c,'declare',{actor:'npc:0_1',kind:'pass',target:'npc:0_2'});assert.throws(()=>cmd(c,'react',{actor:'npc:1_1',response:'intercept'}),/distante/);assert.throws(()=>cmd(c,'react',{actor:'npc:0_2',response:'intercept'}),/adversário/);});
test('rolagens manuais apenas pelo mestre; ajustes antes dos dados',()=>{const c=fixture();c.match.players['npc:0_1'].controller='amigo';resume(c);cmd(c,'declare',{actor:'npc:0_1',kind:'run',to:{x:70,y:34}},'amigo');cmd(c,'advance');assert.throws(()=>cmd(c,'roll',{actor:'npc:0_1',dice:[20]},'amigo'),/mestre/);cmd(c,'adjust',{actor:'npc:0_1',bonus:3,advantage:1,reason:'Talento da ficha'});assert.equal(c.match.pending.tests[0].advantage,1);assert.throws(()=>roll(c,'npc:0_1',[20]),/2 dado/);roll(c,'npc:0_1',[4,10]);assert.equal(c.match.pending,null);});
test('relógio: pausa, intervalo, segundo tempo, snapshot público sem undo',()=>{const c=fixture();resume(c);c.match.elapsed=HALF-500;c.match.anchor=Date.now()-1000;const view=publicMatch(c);assert.equal(view.status,'interval');assert.equal(view.running,false);cmd(c,'half');assert.equal(c.match.half,2);assert.equal(c.match.status,'paused');assert.equal(c.match.elapsed,0);assert.equal(publicMatch(c).undo,undefined);resume(c);cmd(c,'pause');const e=c.match.elapsed;c.match.anchor=Date.now()-10000;assert.equal(publicMatch(c).elapsed,e);});
test('duas abas com revisão antiga não sobrescrevem o campo',()=>{const c=fixture(),rev=c.match.rev;pos(c,'npc:0_1',40,30);assert.throws(()=>cmd(c,'position',{actor:'npc:0_1',to:{x:20,y:20},rev}),/Outra ação/);assert.equal(c.match.players['npc:0_1'].x,40);});
test('cartões e alterações do mestre exigem pausa e motivo',()=>{const c=fixture();resume(c);assert.throws(()=>cmd(c,'correction',{field:'yellow',actor:'npc:0_1',reason:'Falta'}),/Pause/);cmd(c,'pause');cmd(c,'correction',{field:'yellow',actor:'npc:0_1',reason:'Falta'});cmd(c,'correction',{field:'yellow',actor:'npc:0_1',reason:'Segunda falta'});assert.equal(c.match.players['npc:0_1'].red,true);resume(c);assert.throws(()=>cmd(c,'declare',{actor:'npc:0_1',kind:'run',to:{x:55,y:30}}),/expulso/);});
test('críticos: 1 falha, 20 não supera diferença de seis',()=>{assert.equal(wins({natural:1,total:40},{natural:2,total:3}),false);assert.equal(wins({natural:20,total:20},{natural:19,total:25}),true);assert.equal(wins({natural:20,total:20},{natural:19,total:26}),false);});

test('API: clientes sincronizados, corrida concorrente e retomada pausada após restart',async()=>{
 const express=require('express'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {createRpg}=require('../rpg');
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'match-api-')),c=fixture();c.id='CAMPANHA';fs.writeFileSync(path.join(dir,'rpg-campaigns.json'),JSON.stringify({CAMPANHA:c}));let server,url;
 async function boot(){const app=express();const rpg=createRpg({app,express,db:null,normalize:v=>v,dataDir:dir,auth:(req,res,next)=>{req.user={nick:req.headers['x-user']||'mestre'};next();}});await rpg.init();await new Promise(resolve=>{server=app.listen(0,'127.0.0.1',resolve);});url='http://127.0.0.1:'+server.address().port+'/api/rpg/campaigns/CAMPANHA/match';}
 async function request(user,payload){const res=await fetch(url,{method:payload?'POST':'GET',headers:{'x-user':user,'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined});return{status:res.status,data:await res.json()};}
 try{await boot();assert.equal((await request('intruso')).status,403);let m=(await request('mestre')).data.match;
 m=(await request('mestre',{op:'resume',matchId:m.id,rev:m.rev})).data.match;
 const action={op:'declare',actor:'npc:0_1',kind:'run',to:{x:65,y:34},matchId:m.id,rev:m.rev};const results=await Promise.all([request('mestre',action),request('mestre',action)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);
 const a=(await request('mestre')).data.match,b=(await request('amigo')).data.match;assert.equal(a.pending.id,b.pending.id);assert.deepEqual(a.players,b.players);
 await new Promise(resolve=>server.close(resolve));await boot();m=(await request('amigo')).data.match;assert.equal(m.status,'paused');assert.equal(m.running,false);assert.equal(m.pending.id,a.pending.id);assert.equal(m.ball.holder,a.ball.holder);
 const no=(await request('amigo',{op:'resume',matchId:m.id,rev:m.rev}));assert.equal(no.status,403);
 m=(await request('mestre',{op:'resume',matchId:m.id,rev:m.rev})).data.match;
 m=(await request('mestre',{op:'advance',matchId:m.id,actionId:m.pending.id})).data.match;
 const result=await request('mestre',{op:'roll',matchId:m.id,actionId:m.pending.id,actor:'npc:0_1',dice:[12]});assert.equal(result.status,200);assert.equal(result.data.match.pending,null);assert.match(result.data.match.log.find(l=>l.roll).message,/manual/);
 }finally{if(server)await new Promise(resolve=>server.close(resolve));fs.rmSync(dir,{recursive:true,force:true});}
});
