'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),express=require('express'),{createRpg}=require('../rpg');
test('exclusão: permissões, confirmação, conflito, times, NPCs, conta e persistência',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'delete-rpg-'));const c={id:'C',name:'Save',owner:'mestre',members:{mestre:{nick:'mestre'},amigo:{nick:'amigo',sheet:null,lastSheetImport:{id:'old'}}},extras:{'npc:1':{nick:'NPC',sheet:null},'npc:2':{nick:'Escalado',sheet:null}},savedTeams:{t:{name:'Time',ids:['npc:1']},other:{name:'Outro',ids:['npc:2']}},match:{players:{'npc:2':{}}}};
 fs.writeFileSync(path.join(dir,'rpg-campaigns.json'),JSON.stringify({C:c}));const app=express(),r=createRpg({app,express,db:null,dataDir:dir,normalize:s=>s,auth:(req,res,next)=>{req.user={nick:req.headers['x-user']||'mestre'};next();}});await r.init();const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
 const call=async(id,method='GET',body,user='mestre')=>{const res=await fetch(`http://127.0.0.1:${server.address().port}/api/rpg/campaigns/C/sheets/${id}`+(method==='GET'?'/delete-preview':''),{method,headers:{'content-type':'application/json','x-user':user},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json()};};
 try{assert.equal((await call('npc:1','GET',null,'amigo')).status,403);assert.equal((await call('npc:1','DELETE',{confirm:true},'amigo')).status,403);const p=(await call('npc:1')).data;assert.deepEqual(p.teams,['Time']);assert.equal((await call('npc:1','DELETE',{expectedHash:p.expectedHash})).status,400);assert.equal((await call('npc:1','DELETE',{confirm:true,expectedHash:'stale'})).status,409);const blocked=(await call('npc:2')).data;assert.equal(blocked.blocked,true);assert.equal((await call('npc:2','DELETE',{confirm:true,expectedHash:blocked.expectedHash})).status,409);
 // Remove synthetic match before testing successful view serialization.
 c.match=null;await new Promise(resolve=>server.close(resolve));
 }finally{if(server.listening)await new Promise(resolve=>server.close(resolve));fs.rmSync(dir,{recursive:true,force:true});}
});
test('excluir NPC limpa time dependente; excluir ficha mantém participante e grava disco',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'delete-save-')),app=express(),c={id:'C',name:'Save',owner:'mestre',members:{mestre:{nick:'mestre'},amigo:{nick:'amigo',sheet:null,lastSheetImport:{id:'old'}}},extras:{'npc:1':{nick:'NPC',sheet:null}},savedTeams:{t:{name:'Time',ids:['npc:1']}},match:null};fs.writeFileSync(path.join(dir,'rpg-campaigns.json'),JSON.stringify({C:c}));const r=createRpg({app,express,db:null,dataDir:dir,normalize:s=>s,auth:(req,res,next)=>{req.user={nick:'mestre'};next();}});await r.init();const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
 try{for(const id of ['npc:1','amigo']){const url=`http://127.0.0.1:${server.address().port}/api/rpg/campaigns/C/sheets/${id}`,p=await(await fetch(url+'/delete-preview')).json(),res=await fetch(url,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({confirm:true,expectedHash:p.expectedHash})});assert.equal(res.status,200);}const saved=JSON.parse(fs.readFileSync(path.join(dir,'rpg-campaigns.json'))).C;assert.deepEqual(saved.extras,{});assert.deepEqual(saved.savedTeams,{});assert.equal(saved.members.amigo.nick,'amigo');assert.equal(saved.members.amigo.sheet,null);assert.equal(saved.members.amigo.lastSheetImport,undefined);}finally{await new Promise(resolve=>server.close(resolve));fs.rmSync(dir,{recursive:true,force:true});}
});
