'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createHold,HOLD_MS}=require('../public/rpg_pins'),{command}=require('../rpg_match');
function timer(){let now=0,n=0;const timers=new Map(),fired=[];const hold=createHold({fire:p=>fired.push(p),schedule:(fn,ms)=>{const id=++n;timers.set(id,{fn,at:now+ms});return id;},unschedule:id=>timers.delete(id)});return {hold,fired,advance(ms){now+=ms;for(const [id,t] of [...timers])if(t.at<=now){timers.delete(id);t.fn();}}};}
test('marcação exige 2000 ms completos e dispara somente uma vez',()=>{const t=timer();assert.equal(HOLD_MS,2000);t.hold.start({id:1,x:10,y:20});t.advance(1999);assert.equal(t.fired.length,0);t.advance(1);assert.equal(t.fired.length,1);t.advance(5000);assert.equal(t.fired.length,1);});
test('soltar, arrastar, cancelar ou usar segundo dedo interrompe marcação',()=>{for(const cancel of [h=>h.end(1),h=>h.move(1,20,20),h=>h.cancel(),h=>h.start({id:2,x:10,y:20})]){const t=timer();t.hold.start({id:1,x:10,y:20});t.advance(1500);cancel(t.hold);t.advance(1000);assert.equal(t.fired.length,0);}const t=timer();t.hold.start({id:1,x:10,y:20,pinId:'remover'});t.hold.move(1,12,20);t.advance(2000);assert.equal(t.fired[0].pinId,'remover');});
function fixture(){return {owner:'mestre',members:{mestre:{nick:'Mestre'},amigo:{nick:'Amigo'}},match:{id:'M',rev:1,status:'playing',freeMode:true,half:1,elapsed:10,anchor:Date.now(),running:true,players:{a:{id:'a',name:'A',controller:'amigo',team:0,x:10,y:10}},ball:{holder:'a',x:10,y:10},score:[0,0],pending:null,log:[]}};}
function send(c,user,body){command(c,user,{matchId:'M',rev:c.match.rev,...body},s=>s);}
const add={op:'pin',action:'add',pinId:'aaaaaaaaaaaaaaaa',to:{x:50,y:30}};
test('qualquer participante marca e remove, sem mudar jogadores, relógio, dados ou placar',()=>{const c=fixture(),before=structuredClone(c.match);send(c,'amigo',add);assert.equal(c.match.pins[0].by,'Amigo');for(const k of ['players','ball','score','pending','elapsed','anchor','running','log'])assert.deepEqual(c.match[k],before[k]);send(c,'mestre',{op:'pin',action:'remove',pinId:add.pinId});assert.equal(c.match.pins.length,0);});
test('marcação valida acesso e limites, aceita concorrência e não reaparece por repetição',()=>{const c=fixture();assert.throws(()=>send(c,'intruso',add),/participa/);assert.throws(()=>send(c,'amigo',{...add,to:{x:106,y:30}}));assert.throws(()=>send(c,'amigo',{...add,matchId:'outra'}),/partida mudou/);send(c,'amigo',add);send(c,'amigo',add);send(c,'mestre',{...add,pinId:'bbbbbbbbbbbbbbbb',rev:1});assert.equal(c.match.pins.length,2);send(c,'mestre',{op:'pin',action:'remove',pinId:add.pinId});send(c,'amigo',add);assert.equal(c.match.pins.length,1);for(let i=0;i<49;i++)send(c,'amigo',{...add,pinId:'pin-'+String(i).padStart(16,'0')});assert.throws(()=>send(c,'amigo',{...add,pinId:'cccccccccccccccc'}),/Limite/);});
test('desfazer um movimento não desfaz marcações compartilhadas',()=>{const c=fixture();send(c,'amigo',{op:'freeMove',actor:'a',positionRev:0,to:{x:30,y:30}});send(c,'amigo',add);send(c,'mestre',{op:'undo'});assert.equal(c.match.players.a.x,10);assert.equal(c.match.pins[0].id,add.pinId);});
test('API: marcações sincronizadas, concorrentes e persistentes após reinício',async()=>{
 const express=require('express'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{createRpg}=require('../rpg');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pins-api-')),c=fixture();c.id='C';fs.writeFileSync(path.join(dir,'rpg-campaigns.json'),JSON.stringify({C:c}));let server,url;
 async function boot(){const app=express(),r=createRpg({app,express,db:null,dataDir:dir,normalize:s=>s,auth:(req,res,next)=>{req.user={nick:req.headers['x-user']};next();}});await r.init();await new Promise(r=>server=app.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${server.address().port}/api/rpg/campaigns/C/match`;}
 async function req(user,body){const res=await fetch(url,{method:body?'POST':'GET',headers:{'x-user':user,'content-type':'application/json'},body:body?JSON.stringify({matchId:'M',...body}):undefined});return {status:res.status,data:await res.json()};}
 try{await boot();const rs=await Promise.all([req('amigo',add),req('mestre',{...add,pinId:'bbbbbbbbbbbbbbbb'})]);assert.ok(rs.every(r=>r.status===200));assert.equal((await req('amigo')).data.match.pins.length,2);assert.equal((await req('intruso',add)).status,403);await new Promise(r=>server.close(r));await boot();const m=(await req('amigo')).data.match;assert.equal(m.pins.length,2);assert.equal(m.status,'paused');await req('amigo',{op:'pin',action:'remove',pinId:add.pinId});assert.equal((await req('mestre')).data.match.pins.length,1);}finally{if(server)await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}
});
