'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),express=require('express');
const {createRpg,validateSheet,attributes}=require('../rpg');
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
async function context(fn){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'transfer-test-')),sheet=validateSheet({name:'Atleta',age:18,height:180,nationality:'Brasil',level:3,position:'Atacante',style:'Matador',ego:'Rival',base:Object.fromEntries(attributes(false).map(a=>[a,12])),growth:{Finalização:4},photo:png,approved:true,talents:'Talento',weapon:'Arma',notes:'História',cardColor:'#123456'},{},true),c={id:'C',name:'Save',owner:'mestre',members:{mestre:{nick:'Mestre'},amigo:{nick:'Amigo'},outro:{nick:'Outro'}},extras:{'npc:1':{nick:'Modelo',sheet}},notes:'Diário privado',savedTeams:{},match:null};
 fs.writeFileSync(path.join(dir,'rpg-campaigns.json'),JSON.stringify({C:c}));let server,url;
 async function boot(){const app=express(),r=createRpg({app,express,db:null,dataDir:dir,normalize:s=>s,auth:(req,res,next)=>{req.user={nick:req.headers['x-user']};next();}});await r.init();await new Promise(r=>server=app.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${server.address().port}/api/rpg/campaigns/C`;}
 async function req(user,method,suffix='',body){const res=await fetch(url+suffix,{method,headers:{'x-user':user,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json()};}
 try{await boot();await fn({req,sheet,restart:async()=>{await new Promise(r=>server.close(r));await boot();}});}finally{if(server)await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}
}
test('exportação somente pelo mestre contém apenas personagem e foto',()=>context(async({req,sheet})=>{assert.equal((await req('amigo','GET','/sheets/npc:1/export')).status,403);assert.equal((await req('intruso','GET','/sheets/npc:1/export')).status,403);const r=await req('mestre','GET','/sheets/npc:1/export');assert.equal(r.status,200);assert.deepEqual(Object.keys(r.data).sort(),['format','sheet','version']);assert.equal(r.data.sheet.photo,png);assert.equal(r.data.sheet.level,3);assert.equal(r.data.sheet.approved,false);assert.equal(r.data.sheet.stats,undefined);assert.equal(JSON.stringify(r.data).includes('Diário privado'),false);}));
test('prévia não salva; importar mantém dados, vincula à própria conta e persiste sem aprovação',()=>context(async({req,restart})=>{const file=(await req('mestre','GET','/sheets/npc:1/export')).data;file.sheet.approved=true;file.sheet.stats={Finalização:{modifier:999}};const preview=await req('amigo','POST','/import/preview',{file});assert.equal(preview.status,200);assert.equal((await req('amigo','GET')).data.members.amigo.sheet,null);const body={file,expectedHash:preview.data.expectedHash,requestId:'aaaaaaaaaaaaaaaa'};const results=await Promise.all([req('amigo','POST','/import',body),req('amigo','POST','/import',body)]);assert.ok(results.every(r=>r.status===200));await restart();const c=(await req('amigo','GET')).data,s=c.members.amigo.sheet;assert.equal(s.approved,false);assert.equal(s.level,3);assert.equal(s.growth.Finalização,4);assert.equal(s.stats.Finalização.modifier,6);assert.equal(s.photo,png);assert.equal(s.cardColor,'#123456');assert.equal(c.members.outro.sheet,null);assert.equal(c.extras['npc:1'].sheet.approved,true);assert.equal(Object.keys(c.extras).length,1);}));
test('importação valida arquivo, idade, evolução e imagem no servidor',()=>context(async({req})=>{const file=(await req('mestre','GET','/sheets/npc:1/export')).data;for(const bad of [null,{...file,version:99},{...file,sheet:{...file.sheet,age:14}},{...file,sheet:{...file.sheet,growth:{Finalização:29}}},{...file,sheet:{...file.sheet,photo:'data:image/png;base64,AAAA'}},{...file,sheet:{...file.sheet,base:null}}])assert.equal((await req('amigo','POST','/import/preview',{file:bad})).status,400);assert.equal((await req('intruso','POST','/import/preview',{file})).status,403);assert.equal((await req('amigo','GET')).data.members.amigo.sheet,null);}));
test('substituir exige confirmação; ficha aprovada bloqueia importação',()=>context(async({req})=>{const file=(await req('mestre','GET','/sheets/npc:1/export')).data,p=(await req('amigo','POST','/import/preview',{file})).data;await req('amigo','POST','/import',{file,expectedHash:p.expectedHash,requestId:'aaaaaaaaaaaaaaaa'});file.sheet.name='Outra ficha';const p2=(await req('amigo','POST','/import/preview',{file})).data,b={file,expectedHash:p2.expectedHash,requestId:'bbbbbbbbbbbbbbbb'};assert.equal(p2.replacing,true);assert.equal((await req('amigo','POST','/import',b)).status,400);assert.equal((await req('amigo','POST','/import',{...b,replace:true})).status,200);const s=(await req('mestre','GET')).data.members.amigo.sheet;await req('mestre','PUT','/sheets/amigo',{...s,approved:true});assert.equal((await req('amigo','POST','/import/preview',{file})).status,403);assert.equal((await req('amigo','POST','/import',{...b,requestId:'cccccccccccccccc',replace:true})).status,403);}));
test('prévia antiga não sobrescreve edição posterior ou conta diferente',()=>context(async({req,sheet})=>{const file=(await req('mestre','GET','/sheets/npc:1/export')).data,p=(await req('amigo','POST','/import/preview',{file})).data;await req('mestre','PUT','/sheets/amigo',{...sheet,name:'Edição posterior',approved:false});const r=await req('amigo','POST','/import',{file,expectedHash:p.expectedHash,requestId:'aaaaaaaaaaaaaaaa',replace:true,who:'outro'});assert.equal(r.status,409);const c=(await req('amigo','GET')).data;assert.equal(c.members.amigo.sheet.name,'Edição posterior');assert.equal(c.members.outro.sheet,null);}));
