const {test}=require('node:test'),assert=require('node:assert/strict');
const {generate,missing,formations}=require('../public/rpg_npcs');
const {styles,attributes,validateSheet,createRpg}=require('../rpg');
const catalog={styles,line:attributes(false),goalkeeper:attributes(true),egos:['Protagonista']};
test('NPCs respeitam limites em todas as posições, perfis e níveis',()=>{for(const p of Object.keys(styles))for(const l of [1,10,50,100])for(const profile of ['Equilibrada','Ofensiva','Defensiva']){const s=generate(p,l,profile,catalog),v=validateSheet(s,{},true);assert.equal(Object.values(v.growth).reduce((a,b)=>a+b,0),2*(l-1));for(const a of Object.values(v.stats)){assert.ok(a.base>=1&&a.base<=12);assert.ok(a.value<=30);assert.equal(a.modifier,Math.floor((a.value-8)/2)+a.bonus);}assert.ok(v.age>=15&&v.age<=20);}});
test('completar equipe preserva jogadores e exatamente uma vaga de goleiro',()=>{for(const f of Object.keys(formations)){assert.equal(missing(f,[]).length,7);assert.equal(missing(f,[{position:'Atacante'},{position:'Ponta'},{position:'Meio-campo'},{position:'Volante'}]).length,3);assert.equal(missing(f,[{position:'Goleiro'}]).includes('Goleiro'),false);assert.throws(()=>missing(f,[{position:'Goleiro'},{position:'Goleiro'}]));}});
test('lote exige mestre, é atômico, não duplica retry e persiste',async()=>{const express=require('express'),fs=require('fs'),os=require('os'),path=require('path'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'npc-test-'));const c={id:'C',name:'Teste',owner:'mestre',members:{mestre:{},amigo:{}},extras:{}};fs.writeFileSync(path.join(dir,'rpg-campaigns.json'),JSON.stringify({C:c}));const app=express(),r=createRpg({app,express,db:null,dataDir:dir,normalize:v=>v,auth:(req,res,next)=>{req.user={nick:req.headers['x-user']};next();}});await r.init();const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.on('listening',resolve));const url=`http://127.0.0.1:${server.address().port}/api/rpg/campaigns/C/extras/batch`;
const sheets=formations['2-3-1'].map(p=>generate(p,10,'Equilibrada',catalog));async function send(user,requestId,ss=sheets){const res=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-user':user},body:JSON.stringify({sheets:ss,requestId})});return {status:res.status,data:await res.json()};}
try{assert.equal((await send('amigo','aaaaaaaaaaaaaaaa')).status,403);assert.equal((await send('mestre','bbbbbbbbbbbbbbbb',[sheets[0],{...sheets[1],age:14}])).status,400);let results=await Promise.all([send('mestre','cccccccccccccccc'),send('mestre','cccccccccccccccc')]);for(const r of results){assert.equal(r.status,200);assert.equal(Object.keys(r.data.extras).length,7);}assert.equal(Object.keys(JSON.parse(fs.readFileSync(path.join(dir,'rpg-campaigns.json'))).C.extras).length,7);for(let i=0;i<3;i++)assert.equal((await send('mestre',String(i).repeat(16))).status,200);assert.equal((await send('mestre','dddddddddddddddd')).status,400);}finally{await new Promise(resolve=>server.close(resolve));fs.rmSync(dir,{recursive:true,force:true});}});
